### PR TITLE
Implemented the functionality of the Create Instrument Addon.vi

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

The implementation of the Create Instrument Addon.vi was added. A unit test which validates the functionality of the create node was also added. 
All tests which were NOT closing the System Definition, Target and Root Refnums in the tearDown.vi were updated.
tearDown.vi-s were updated.

### Why should this Pull Request be merged?

The Create Instrument Addon.vi was added to the scripting API but it was lacking functionality.
The tests were calling the close reference node within the tests, instead closing the references once the test finished executing.

### What testing has been done?

Run the tests locally and they passed.

### CODE REVIEW

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
Please revert the unwanted files (I saw some Data Channels tests).

**Comment by bogdanp-ni** [comment]
Regarding tearDown.vi - there's a small correction that's needed:
image

In the case when "error in" comes with an error, the first Close will not execute (if Target Refnum is valid). That first Case Structure should be identical with the other three, and the "error in" must be wired directly to the final Merge Errors.

**Comment by bogdanp-ni** [comment]
Create Instrument Addon Node.vi => the "Node" part of this name is not exactly self-explanatory. I believe a rename would help, something like "Instantiate Default Instrument Addon" or "Create Default Instrument Addon".

**Comment by bogdanp-ni** [comment]
[Recommend] I really appreciate you proactively cleaning up all references from these unit tests. We should strive to have the actual test code as clean as possible, free of any "infrastructure code" needed to set up or destroy the test conditions. As a lesson learned: for future test classes, if a single sysdef file is to be used for all test cases, opening all references can be moved in the setUp VI, and necessary references can be fetched from the test object's properties.

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
The change looks good overall. I had two relatively minor comments that I would like to see addressed before accepting.

**Comment by phutanu** [comment]
> Regarding tearDown.vi - there's a small correction that's needed:
> image
> 
> In the case when "error in" comes with an error, the first Close will not execute (if Target Refnum is valid). That first Case Structure should be identical with the other three, and the "error in" control must be wired directly to the final Merge Errors.

I tested this by curiosity and did a mock Test Class with a test that always gives an error. The error from the test is not passed through to the "tearDown.vi".

**Comment by phutanu** [comment]
Create Instrument Addon From Configuration File.vi -> the false case would need some small cleanup. I care about this because the API will be public.

image

**Comment by phutanu** [comment]
[Recommendation] I do appreciate taking your time to refactor all the current tests. 
For future, [CTRL+ALT] + Mouse Left Click can make miracles for the extra space that remains after some nodes removal.
I noticed this especially in the test Protocols VIs.

image

**Review by phutanu — APPROVED** [review]
Except the small visual inside the "Create Instrument Addon From Configuration File.vi" I am ok with this change.

**Comment by zszilagy** [comment]
> Create Instrument Addon From Configuration File.vi -> the false case would need some small cleanup. I care about this because the API will be public.
> 
> image

The case was cleaned up.

**Comment by zszilagy** [comment]
> > Regarding tearDown.vi - there's a small correction that's needed:
> > image
> > In the case when "error in" comes with an error, the first Close will not execute (if Target Refnum is valid). That first Case Structure should be identical with the other three, and the "error in" control must be wired directly to the final Merge Errors.
> 
> I tested this by curiosity and did a mock Test Class with a test that always gives an error. The error from the test is not passed through to the "tearDown.vi".

Even though it does not influence the outcome of the tests, for the sake of matching implementation, I implemented the bogdanp-ni's suggestion.

**Comment by zszilagy** [comment]
> Create Instrument Addon Node.vi => the "Node" part of this name is not exactly self-explanatory. I believe a rename would help, something like "Instantiate Default Instrument Addon" or "Create Default Instrument Addon".

The subvi was renamed to "Create Default Instrument Addon.vi".

**Comment by zszilagy** [comment]
> The change looks good overall. I had two relatively minor comments that I would like to see addressed before accepting.

Resolved all the comments!

**Review by phutanu — APPROVED** [review]
Congrats @zszilagy for going above and beyond your appointed tasks! 👍 👍 👍

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
