### PR TITLE
Add System Level Tests for Single Channel Command and Command Response

### PR DESCRIPTION
**Pull request by phutanu**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?
Add System Level Tests for Single Channel Command and Command Response Messages.

### Why should this Pull Request be merged?
In order to add the Tests to the official repo.

### What testing has been done?
All systems tests have run successfully using VI Tester.

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
TCP Data Reader: is this error out left hanging on purpose?

image

**Comment by phutanu** [comment]
> TCP Data Reader: is this error out left hanging on purpose?
> 
> image

Yeah, I do not want it to influence the test further if the reference is already closed or missing.

**Comment by bogdanp-ni** [comment]
TCP HeartBeat Generator: in the event that the port 8889 is already in use on the machine running the test, this TCP node will hang indefinitely. I'd prefer you add a reasonable timeout value. Timing out must cause a transparent test failure, which should be easy to track down.

image

**Comment by bogdanp-ni** [comment]
TCP HeartBeat Generator: improve icon

**Comment by bogdanp-ni** [comment]
TCP Listener: improve icon

**Comment by bogdanp-ni** [comment]
TCP Listener: same for using a timeout value on calling TCP Listen

**Comment by phutanu** [comment]
> TCP HeartBeat Generator: improve icon

Done

**Comment by phutanu** [comment]
> TCP Listener: improve icon

Done

**Comment by phutanu** [comment]
> TCP HeartBeat Generator: in the event that the port 8889 is already in use on the machine running the test, this TCP node will hang indefinitely. I'd prefer you add a reasonable timeout value. Timing out must cause a transparent test failure, which should be easy to track down.
> 
> image

Done

**Comment by phutanu** [comment]
> TCP Listener: same for using a timeout value on calling TCP Listen

Done

**Comment by bogdanp-ni** [comment]
There are some tests where you also check that a periodic message is getting sent. Please rename those VIs to include that information. Something like "test_Periodic and Multiple Static ..."

**Comment by bogdanp-ni** [comment]
Remove the word "EXAMPLE" from all test icons. Leave the rest of the icon template. Since the test names are long and descriptive, they will not fit in the icon, so I'd prefer we just have the template and no test in it.

**Comment by phutanu** [comment]
> There are some tests where you also check that a periodic message is getting sent. Please rename those VIs to include that information. Something like "test_Periodic and Multiple Static ..."

Done

**Comment by phutanu** [comment]
> Remove the word "EXAMPLE" from all test icons. Leave the rest of the icon template. Since the test names are long and descriptive, they will not fit in the icon, so I'd prefer we just have the template and no test in it.

Done

**Pull request merged**
