### PR TITLE
IA - Implementation of the "Create Instrument Addon from Configuration File.vi" scripting API

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

 -   Completed the Create Instrument Addon from Configuration File.vi part of the API
 -  Created a test case for the Create Instrument Addon from Configuration File.vi API
 -   Created a template Icon for the Instrument Addon Scripting API.lvlib ... to be modified if necessary

### Why should this Pull Request be merged?

Implements part of the Instrument Addon Scripting API -> creating an Instrument Addon CD from configuration file. Adds a default Icon template for the Instrument Addon Scripting API.lvlib

### What testing has been done?

 - Created a test case for the Create Instrument Addon from Configuration File.vi API. Tested locally

### CODE REVIEW

**Review by phutanu — COMMENTED** [review]
- Have you checked the refactor of the Initialization.vi from System Explorer? The functionality there is similar with what this scripting API node is doing.
- Also documentation and help page is required for the scripting node.

**Comment by bogdanp-ni** [comment]
Could you please add an error test case? Also, is the error code the same one that's thrown when using the System Explorer?

**Comment by DStavilaNI** [comment]
> 
> 
>     * Have you checked the refactor of the Initialization.vi from System Explorer? The functionality there is similar with what this scripting API node is doing.
> 
>     * Also documentation and help page is required for the scripting node.

- Yes, I did check the Initialization.vi from System Explorer. Is there something specific you want to point at ? 
- Yes, I do intend to add documentation to this API. At this point it is still under construction, and I only want to add a context help to the relevant VIs, considering the API changes that were discussed with and approved by Bogdan. I think it would make more sense to document the API once we have something close to the final version of it ... at this point, I would still expect a lot of changes.

**Comment by DStavilaNI** [comment]
> 
> 
> Could you please add an error test case? Also, is the error code the same one that's thrown when using the System Explorer?

The IA System Explorer, as it is, does not throw any errors if you do not provide a configuration file. It simply builds the IA Custom Device with a default configuration.  I thought that this is not the desired behavior for this VI, considering that this piece of API is supposed to explicitly build a CD using a configuration file. 

Sure, I can add an error test case for it.

**Comment by phutanu** [comment]
> * Yes, I did check the Initialization.vi from System Explorer. Is there something specific you want to point at ?

If we can, we want to avoid functionality duplication, and this scripting node is duplicating code from the Initialization.vi. If it is feasible we would want to replace the creation of an addon from a config file code in the Initialization.vi with the newly created scripting node.

**Comment by DStavilaNI** [comment]
> 
> 
> > * Yes, I did check the Initialization.vi from System Explorer. Is there something specific you want to point at ?
> 
> If we can, we want to avoid functionality duplication, and this scripting node is duplicating code from the Initialization.vi. If it is feasible we would want to replace the creation of an addon from a config file code in the Initialization.vi with the newly created scripting node.

I agree with the principle of avoiding duplication. However, in this case, even though I am using some of the same functions, there is no duplication and the code cannot be replaced. This particular piece of API creates a new CD within the referenced target using the provided config file. The "Initialization.vi" is being called immediately after a CD is created and added to the Sysdef -> putting this SubVI inside the "Initialization.vi", will have the effect of creating an additional CD, under the same target.

**Comment by DStavilaNI** [comment]
> 
> 
> Could you please add an error test case? Also, is the error code the same one that's thrown when using the System Explorer?

Done

**Comment by phutanu** [comment]
Please solve the conflicted files.

**Comment by DStavilaNI** [comment]
> 
> 
> Please solve the conflicted files.

Solved

**Pull request merged**
