### PR TITLE
Added 10 unit tests for Format Numeric To String.vi

### PR DESCRIPTION
**Pull request by zszilagy**
10 new tests were added which verifies the Format Numeric To String.vi functionality

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Please rename the files according to the convention: test_DUT Name_test case details
Use only those 2 underscores, don't use PascalCase. Make sure the names are shorter, because the diffing tool had problems and I believe it's because of the long pathnames.

**Comment by bogdanp-ni** [comment]
Delete temp_VI_UnderTest.vi

**Comment by zszilagy** [comment]
> Delete temp_VI_UnderTest.vi

The file was removed

**Comment by zszilagy** [comment]
> Please rename the files according to the convention: test_DUT Name_test case details
> Use only those 2 underscores, don't use PascalCase. Make sure the names are shorter, because the diffing tool had problems and I believe it's because of the long pathnames.

The files were renamed

**Pull request closed without merging**
