### PR TITLE
Refactored the Create Message.vi polymorphic VI to match the current design guidelines

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Arranged Front Panel with Ctrl+Space,Ctrl+F
- Arranged Block Diagram with Ctrl+Space,Ctrl+F
- Changed control/indicator label to lower case letters
- Added description to the VIs (Description contains parts from the original documentation)

### Why should this Pull Request be merged?

The current version of the VI does not meet the design guidelines.

### What testing has been done?

n/a

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
This must be "optional settings", for all three VIs:

image

**Comment by bogdanp-ni** [comment]
"period (s)" must be of type U32:

image

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See comments above

**Comment by phutanu** [comment]
For all three nodes, according with the HLD document:
"message group in" -> should be "message group **refnum** in"
"message group out" -> should be "message group **refnum** out"

image

**Review by phutanu — CHANGES_REQUESTED** [review]
For all three nodes, according with the HLD document:
"message group in" -> should be "message group **refnum** in"
"message group out" -> should be "message group **refnum** out"

Also please correct the missing "r" typo in "message g _r_oup out" for two of the nodes.

image

**Comment by phutanu** [comment]
> This must be "optional settings", for all three VIs:
> 
> image

The first option in the TypeDef should be "Protection".

image

**Comment by zszilagy** [comment]
> This must be "optional settings", for all three VIs:
> 
> image

Changed in the VIs and in the type def.

**Comment by zszilagy** [comment]
> "period (s)" must be of type U32:
> 
> image

Changed in the API VI and the VI which processes the value (Instrument Addon Scripting API.lvlibLSet Message Period.vi), however the coercion can't be avoided on lower levels (VS API)

**Comment by zszilagy** [comment]
> For all three nodes, according with the HLD document:
> "message group in" -> should be "message group **refnum** in"
> "message group out" -> should be "message group **refnum** out"
> 
> Also please correct the missing "r" typo in "message g _r_oup out" for two of the nodes.
> 
> image

Fixed.

**Comment by zszilagy** [comment]
> > This must be "optional settings", for all three VIs:
> > image
> 
> The first option in the TypeDef should be "Protection".
> And "Trigger Channel refnum" (refnum with small r).
> 
> image

Fixed in type def.

**Comment by phutanu** [comment]
Create Message - Value Change & Trigger.vi -> Please connect the "message group refnum in" to "message group refnum out" inside the Error Case.

**Review by phutanu — CHANGES_REQUESTED** [review]
Please address my small comment from above, and this PR is good to go.

**Comment by zszilagy** [comment]
> I really appreciate you going above & beyond, so one small thing is missing for the refactor in the below VI.
> 
> Create Message - Value Change & Trigger.vi -> Please connect the "message group refnum in" to "message group refnum out" inside the Error Case.
> 
> image

Missed this one. Fixed as requested.

**Review by phutanu — APPROVED** [review]

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
