### PR TITLE
Updated Create * Channel Polymorphic VIs to meet the design guidelines 

### PR DESCRIPTION
**Pull request by csteavu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

For each of the Create * Channel (the 3 polymorphic VIs) the following actions were performed if necessary:

- Arranged Front Panel with Ctrl+Space,Ctrl+F
- Arranged Block Diagram with Ctrl+Space,Ctrl+F
- Changed control/indicator label to lower case letters
- Added description to the VIs (Description contains parts from the original documentation)

### Why should this Pull Request be merged?

The current version of the VI does not meet the design guidelines.

### What testing has been done?

N/A

### CODE REVIEW

**Comment by phutanu** [comment]
"channel name" input should be required for all nodes.

**Comment by phutanu** [comment]
Create Data Channel - Array - Comparison.vi - "Array" in settings typedef should be renamed to "Elements" to be more consistent with the other nodes.

**Comment by phutanu** [comment]
Create Data Channel - Array - Type Cast.vi -> The order inside the typedef should be the one from the HLD doc:

image

**Comment by phutanu** [comment]
Create Data Channel - Single Channel - Type Cast.vi -> The order should be as below, for consistency with the array node one.

image

**Comment by phutanu** [comment]
For all four "Create Data Channel - Array" the "Add Array Data Channel.vi" needs to be updated as it is currently outputting the wrong channel values (it's outputting an array of parent refs and not of the actual channels).
 
image

The "Channel Refnums" needs to be change to an element and have the name "array refnum"
And the "Channel Refs" needs to be given out to the "Create Data Channel - Array" node.

Finally, the "Create Data Channel - Array" for all the four options (Enum, Format, TypeCast, Comparison) should have also the "array refnum" output along with the "channel refnums".

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check my above comments.

**Comment by zszilagy** [comment]
> "channel name" input should be required for all nodes.

Fixed.

**Comment by zszilagy** [comment]
> Create Data Channel - Array - Comparison.vi - "Array" in settings typedef should be renamed to "Elements" to be more consistent with the other nodes.

Fixed.

**Comment by zszilagy** [comment]
> Array Type Cast Settings.ctl -> The order inside the typedef should be the one from the HLD doc:
> 
> * Then all the Array Type Cast Create VIs (Data, MetaData & Global MetaData) should be saved with the new updated typedef.
> 
> image

Fixed.

**Comment by zszilagy** [comment]
> Single Channel Type Cast Settings.ctl -> The order should be as in the picture below, for consistency with the array type cast ctl.
> 
> * Then all the Single Channel Type Cast Create VIs (Data, MetaData & Global MetaData) should be saved with the new updated typedef.
> 
> image

Fixed.

**Comment by zszilagy** [comment]
> For all four "Create Data Channel - Array" the "Add Array Data Channel.vi" needs to be updated as it is currently outputting the wrong channel values (it's outputting an array of parent refs and not of the actual channels).
> 
> image
> 
> The "Channel Refnums" needs to be change to an element and have the name "array refnum"
> And the "Channel Refs" needs to be given out to the "Create Data Channel - Array" node.
> 
> Finally, the "Create Data Channel - Array" for all the four options (Enum, Format, TypeCast, Comparison) should have also the "array refnum" output along with the "channel refnums".

Fixed

**Review by phutanu — APPROVED** [review]

**Pull request merged**
