### PR TITLE
IA Get and Set Protocol.vi - API implementation

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Implemented the Get and Set Protocol.vi API, together with the test VIs.
- Changed the errors for "Create Instrument Addon From Configuration File.vi" and "Export Instrument Addon Configuration.vi" to positive values for consistency across all the Scripting API VIs.
- Fixed the failing "test_Export Instrument Addon Config with Error.vi".

### Why should this Pull Request be merged?

- Implements the Get and Set Protocol.vi API.
- Implements test VIs for the Get and Set Protocol.vi API
- Added documentation for the Get and Set Protocol.vi API
- Updates two VIs with approved error codes.
- Fixes a failing test: "test_Export Instrument Addon Config with Error.vi".

### What testing has been done?
- Test VIs have been created to test the API functionality
- Both normal test cases and error test case has been implemented.

### CODE REVIEW

**Comment by phutanu** [comment]
For "Set Protocol.vi": Please connect the Error Wire coming from the "Validate Instrument Addon Refnum.vi" straight through in the "False" case as the wire will already have the Error Information required.

image

**Comment by phutanu** [comment]
Please adjust this error code from "Set Protocol.vi" according with the next available code number from the Error Codes Document from our Teams Wiki. Please do not forget to add the new error code info in our doc.

image

**Comment by phutanu** [comment]
For "Get Protocol.vi" please update the error codes as well with the ones available in the Error Doc from Teams Wiki.

image

**Comment by phutanu** [comment]
> For "Set Protocol.vi": Please connect the Error Wire coming from the "Validate Instrument Addon Refnum.vi" straight through in the "False" case as the wire will already have the Error Information required.
> 
> image

Please do the same thing for "Get Protocol.vi".

**Comment by phutanu** [comment]
Usually, for the unit tests we try to keep this naming convention: test_[vi name under test]_[what we test].vi
So a better option for the current tests added that should not generate confusion when using the Dashboard would be:

-from-> "test_VI Set_Get Protocol UDP.vi" -to-> "test_Set-Get Protocol UDP.vi"

Please update this for all the tests.

**Comment by DStavilaNI** [comment]
> 
> 
> For "Set Protocol.vi": Please connect the Error Wire coming from the "Validate Instrument Addon Refnum.vi" straight through in the "False" case as the wire will already have the Error Information required.
> 
> image

Why ? Is it a styling problem or something else ? Please elaborate.

**Comment by DStavilaNI** [comment]
> 
> 
> For all the submitted tests, we need to add a check beforehand that the current protocol settings in the Instrument Addon are different than the settings we add using the "Set Protocol" node.
> If the current protocol settings in the Instrument Addon are identical with the values we add in the test, the test will not identify errors in the "Set/Get Protocol" nodes.

Did you happen to check the implementation of the "Set Protocol.vi" ? What it does is that essentially it overwrites any existing settings for the selected protocol. Checking beforehand does not make to much sense in this case, since any existing values will be replaced either way.

**Comment by DStavilaNI** [comment]
> 
> 
> Usually, for the unit tests we try to keep this naming convention: test_[vi name under test]_[what we test].vi
> So a better option for the current tests added that should not generate confusion when using the Dashboard would be:
> 
> -from-> "_test_VI Set_Get Protocol UDP.vi_" -to-> "**test_Set-Get Protocol UDP.vi**"
> 
> Please update this for all the tests.

Sure

**Comment by DStavilaNI** [comment]
> 
> 
> For "Get Protocol.vi" please update the error codes as well with the ones available in the Error Doc from Teams Wiki.
> 
> image

Sure

**Comment by phutanu** [comment]
> > For all the submitted tests, we need to add a check beforehand that the current protocol settings in the Instrument Addon are different than the settings we add using the "Set Protocol" node.
> > If the current protocol settings in the Instrument Addon are identical with the values we add in the test, the test will not identify errors in the "Set/Get Protocol" nodes.
> 
> Did you happen to check the implementation of the "Set Protocol.vi" ? What it does is that essentially it overwrites any existing settings for the selected protocol. Checking beforehand does not make to much sense in this case, since any existing values will be replaced either way.

From my point of view, looking at how this tests are done, I can say they validate only that the "Get Protocol.vi" node is doing what is supposed to do. I do not see them validate that the "Set Protocol" indeed overrides everything as we do not know what was already set beforehand.

I see two options:
1. Checking what is already set using a "Get" before the already implemented "Set" and "Get".
2. Or by doing another round of "Set" and "Get" with different values than the ones already used.

**Comment by phutanu** [comment]
> > For "Set Protocol.vi": Please connect the Error Wire coming from the "Validate Instrument Addon Refnum.vi" straight through in the "False" case as the wire will already have the Error Information required.
> 
> Why ? Is it a styling problem or something else ? Please elaborate.

We would like to avoid having too many error rings that basically return the same error information. It would be a big overhead to change error code rings spread all over the code, especially keeping consistency when we have two (or more) error rings for basically the same check.

> The original idea there was to re-use the error ring, to display some meaningful information to whoever checks the code, instead of having an empty case.

You can do that by adding a label inside the case that says what you think would be helpful for whoever checks the code.

> Still, as a side note - if the "Validate Instrument Addon Refnum.vi" throws an error if the CD is incorrect, then what's the point of the "Is Valid?" output terminal ? Isn't it redundant information ?

Yeah, it's redundant if you think of it that way.

**Comment by phutanu** [comment]
> > Usually, for the unit tests we try to keep this naming convention: test_[vi name under test]_[what we test].vi
> > So a better option for the current tests added that should not generate confusion when using the Dashboard would be:
> > -from-> "_test_VI Set_Get Protocol UDP.vi_" -to-> "**test_Set-Get Protocol UDP.vi**"
> > Please update this for all the tests.
> 
> Sure

Please remove also the "VI" from all the tests naming.

**Comment by phutanu** [comment]
> > For "Get Protocol.vi" please update the error codes as well with the ones available in the Error Doc from Teams Wiki.
> > image
> 
> Sure

-5008 and -5009 are not in the range of custom error codes ranges defined by LabVIEW. This ranges are defined in the documentation as:
- -8999 through -8000
- 5000 through 9999
- 500,000 through 599,999

Is there a reason you used this negative error codes?

We would prefer to continue incremental from the current values and you can use positive 5008 and 5009.

**Comment by DStavilaNI** [comment]
> 
> 
> > > Usually, for the unit tests we try to keep this naming convention: test_[vi name under test]_[what we test].vi
> > > So a better option for the current tests added that should not generate confusion when using the Dashboard would be:
> > > -from-> "_test_VI Set_Get Protocol UDP.vi_" -to-> "**test_Set-Get Protocol UDP.vi**"
> > > Please update this for all the tests.
> > 
> > 
> > Sure
> 
> Please remove also the "VI" from all the tests naming.

Why ?  Again, I would like to understand the benefit of this feedback - is there any objective reason to it ?

**Comment by DStavilaNI** [comment]
> 
> 
> > > For "Get Protocol.vi" please update the error codes as well with the ones available in the Error Doc from Teams Wiki.
> > > image
> > 
> > 
> > Sure
> 
> -5008 and -5009 are not in the range of custom error codes ranges defined by LabVIEW. This ranges are defined in the documentation as:
> 
>     * -8999 through -8000
> 
>     * 5000 through 9999
> 
>     * 500,000 through 599,999
> 
> 
> Is there a reason you used this negative error codes?
> 
> We would prefer to continue incremental from the current values and you can use positive 5008 and 5009.

There is no specific reason - I prefer negative error codes. Also, we did not have in place a convention regarding error codes before we started working on this.  Still, why wasn't this feedback included in the previous comments regarding error codes ? It does not make sense to all the time work on and apply partial feedbacks - I believe it causes unnecessary delays for the PRs.

**Comment by DStavilaNI** [comment]
> 
> 
> > > For all the submitted tests, we need to add a check beforehand that the current protocol settings in the Instrument Addon are different than the settings we add using the "Set Protocol" node.
> > > If the current protocol settings in the Instrument Addon are identical with the values we add in the test, the test will not identify errors in the "Set/Get Protocol" nodes.
> > 
> > 
> > Did you happen to check the implementation of the "Set Protocol.vi" ? What it does is that essentially it overwrites any existing settings for the selected protocol. Checking beforehand does not make to much sense in this case, since any existing values will be replaced either way.
> 
> From my point of view, looking at how this tests are done, I can say they validate only that the "Get Protocol.vi" node is doing what is supposed to do. I do not see them validate that the "Set Protocol" indeed overrides everything as we do not know what was already set beforehand.
> 
> I see two options:
> 
>     1. Checking what is already set using a "Get" before the already implemented "Set" and "Get".
> 
>     2. Or by doing another round of "Set" and "Get" with different values than the ones already used.

The whole point of the test structure is that the "Get" validates the "Set", and essentially they validate each other. The validation criteria is that the object that goes in is the same as the one that comes out. There is indeed the possibility that what is already inside the system definition is the same as the newly created protocol object - if this is true, I still don't see the problem for several reasons:
 - It can be very well a real-life scenario. A developer may attempt to apply a new Protocol to the Custom Device, and that Protocol could be indeed already set. The Set or Get Protocol VIs should work in this case as well as expected.
- Referring specifically to the test VIs - the content of the used System Definition file is KNOWN before the beginning of the tests: i.e. the protocol is set to a specific value, which is different from the value set by the first test VI. The initial protocol is AK RS-xxx and the first test VI is setting the VISA protocol.   
- Each test saves the System Definition after applying the modification (after applying a protocol), which means that the next test is setting a different protocol. 
- When developing the tests, I made sure to check the default values when creating a new IA Custom Device with a given protocol, so that when the "Set Protocol.vi" is running I can be certain that new and different values are applied each time.

**Comment by bogdanp-ni** [comment]
> > > > For all the submitted tests, we need to add a check beforehand that the current protocol settings in the Instrument Addon are different than the settings we add using the "Set Protocol" node.
> > > > If the current protocol settings in the Instrument Addon are identical with the values we add in the test, the test will not identify errors in the "Set/Get Protocol" nodes.
> > > 
> > > 
> > > Did you happen to check the implementation of the "Set Protocol.vi" ? What it does is that essentially it overwrites any existing settings for the selected protocol. Checking beforehand does not make to much sense in this case, since any existing values will be replaced either way.
> > 
> > 
> > From my point of view, looking at how this tests are done, I can say they validate only that the "Get Protocol.vi" node is doing what is supposed to do. I do not see them validate that the "Set Protocol" indeed overrides everything as we do not know what was already set beforehand.
> > I see two options:
> > ```
> > 1. Checking what is already set using a "Get" before the already implemented "Set" and "Get".
> > 
> > 2. Or by doing another round of "Set" and "Get" with different values than the ones already used.
> > ```
> 
> The whole point of the test structure is that the "Get" validates the "Set", and essentially they validate each other. The validation criteria is that the object that goes in is the same as the one that comes out. There is indeed the possibility that what is already inside the system definition is the same as the newly created protocol object - if this is true, I still don't see the problem for several reasons:
> 
> * It can be very well a real-life scenario. A developer may attempt to apply a new Protocol to the Custom Device, and that Protocol could be indeed already set. The Set or Get Protocol VIs should work in this case as well as expected.
> * Referring specifically to the test VIs - the content of the used System Definition file is KNOWN before the beginning of the tests: i.e. the protocol is set to a specific value, which is different from the value set by the first test VI. The initial protocol is AK RS-xxx and the first test VI is setting the VISA protocol.
> * Each test saves the System Definition after applying the modification (after applying a protocol), which means that the next test is setting a different protocol.
> * When developing the tests, I made sure to check the default values when creating a new IA Custom Device with a given protocol, so that when the "Set Protocol.vi" is running I can be certain that new and different values are applied each time.
> 
> Regarding the options you are mentioning:
> 
> 1. I run a "Get", and let's assume (even though, as I mentioned, the content of the SysDef before the beginning of the test is already known) that the found protocol object is the same as the one I am about to set - then what ? does it mean that the test fails ? I think that this idea is incomplete ...
> 2. It is a chicken and egg problem in this case - so we assume that the first pair of "Set" and "Get" is working, or does something, somehow to the System Definition, and the second pair is actually the one being tested, while the API used in both cases is the same ? What does it prove ? I think it would only increase the degree of uncertainty...
> 
> The best degree of certainty, in this case, in my opinion, is given by the fact that the content of the SysDef is known before the tests are running.

See my similar comment on this PR: https://github.com/ni/niveristand-instrument-addon-custom-device/pull/85

I believe that we should first test the GET, then the SET. Testing the GET on the initial value from the sysdef makes sense, since we already know the value from that file (it was configured by us). It also safeguards against unwanted changes to the sysdef. Testing the SET must be done by writing a different value from the one already persisted in the sysdef file (hence the need for the first GET, making sure we know the initial state) and then performing another GET, to check that the new value was correctly persisted.

**Comment by phutanu** [comment]
> > > > For all the submitted tests, we need to add a check beforehand that the current protocol settings in the Instrument Addon are different than the settings we add using the "Set Protocol" node.
> > > > If the current protocol settings in the Instrument Addon are identical with the values we add in the test, the test will not identify errors in the "Set/Get Protocol" nodes.
> > > 
> > > 
> > > Did you happen to check the implementation of the "Set Protocol.vi" ? What it does is that essentially it overwrites any existing settings for the selected protocol. Checking beforehand does not make to much sense in this case, since any existing values will be replaced either way.
> > 
> > 
> > From my point of view, looking at how this tests are done, I can say they validate only that the "Get Protocol.vi" node is doing what is supposed to do. I do not see them validate that the "Set Protocol" indeed overrides everything as we do not know what was already set beforehand.
> > I see two options:
> > ```
> > 1. Checking what is already set using a "Get" before the already implemented "Set" and "Get".
> > 
> > 2. Or by doing another round of "Set" and "Get" with different values than the ones already used.
> > ```
> 
> The whole point of the test structure is that the "Get" validates the "Set", and essentially they validate each other. The validation criteria is that the object that goes in is the same as the one that comes out. There is indeed the possibility that what is already inside the system definition is the same as the newly created protocol object - if this is true, I still don't see the problem for several reasons:
> 
> * It can be very well a real-life scenario. A developer may attempt to apply a new Protocol to the Custom Device, and that Protocol could be indeed already set. The Set or Get Protocol VIs should work in this case as well as expected. 
> * Referring specifically to the test VIs - the content of the used System Definition file is KNOWN before the beginning of the tests: i.e. the protocol is set to a specific value, which is different from the value set by the first test VI. The initial protocol is AK RS-xxx and the first test VI is setting the VISA protocol.
> * Each test saves the System Definition after applying the modification (after applying a protocol), which means that the next test is setting a different protocol.
> * When developing the tests, I made sure to check the default values when creating a new IA Custom Device with a given protocol, so that when the "Set Protocol.vi" is running I can be certain that new and different values are applied each time.
> 
> Regarding the options you are mentioning:
> 
> 1. I run a "Get", and let's assume (even though, as I mentioned, the content of the SysDef before the beginning of the test is already known) that the found protocol object is the same as the one I am about to set - then what ? does it mean that the test fails ? I think that this idea is incomplete ...

It should fail if we expect something else there, as you already explained, we shouldn't have the same protocol object based on the current test setup.

> 2. It is a chicken and egg problem in this case - so we assume that the first pair of "Set" and "Get" is working, or does something, somehow to the System Definition, and the second pair is actually the one being tested, while the API used in both cases is the same ? What does it prove ? I think it would only increase the degree of uncertainty...

If we set totally different values for the protocol settings in the first "Set" and "Get" pair, then test that we have what we set, then do the the second pair of "Set" and "Get" and test for the new values, that for me is the biggest certainty that both nodes do what they should, and that we do not need to rely on the fact the system definition contains what was saved by the previous test,

> 
> The best degree of certainty, in this case, in my opinion, is given by the fact that the content of the SysDef is known before the tests are running.

One other thing we may encounter, is for developers to run the same test two consecutive times on the development machine. Using this setup, when running for the second consecutive time the same test, this test does not really validates anything as we have the same protocol and settings already saved in the system definition.

**Comment by bogdanp-ni** [comment]
Thanks for taking the initiative and fixing Create Instrument Addon From Configuration File.vi and Export Instrument Addon Configuration! The error codes list was something that I should have put in place from the beginning, so lesson learned there 😁

**Comment by DStavilaNI** [comment]
> 
> 
> Thanks for taking the initiative and fixing Create Instrument Addon From Configuration File.vi and Export Instrument Addon Configuration! The error codes list was something that I should have put in place from the beginning, so lesson learned there 😁

Anytime :) ... that's what we do :D

**Comment by DStavilaNI** [comment]
> 
> 
> > > > > For all the submitted tests, we need to add a check beforehand that the current protocol settings in the Instrument Addon are different than the settings we add using the "Set Protocol" node.
> > > > > If the current protocol settings in the Instrument Addon are identical with the values we add in the test, the test will not identify errors in the "Set/Get Protocol" nodes.
> > > > 
> > > > 
> > > > Did you happen to check the implementation of the "Set Protocol.vi" ? What it does is that essentially it overwrites any existing settings for the selected protocol. Checking beforehand does not make to much sense in this case, since any existing values will be replaced either way.
> > > 
> > > 
> > > From my point of view, looking at how this tests are done, I can say they validate only that the "Get Protocol.vi" node is doing what is supposed to do. I do not see them validate that the "Set Protocol" indeed overrides everything as we do not know what was already set beforehand.
> > > I see two options:
> > > ```
> > > 1. Checking what is already set using a "Get" before the already implemented "Set" and "Get".
> > > 
> > > 2. Or by doing another round of "Set" and "Get" with different values than the ones already used.
> > > ```
> > 
> > 
> > The whole point of the test structure is that the "Get" validates the "Set", and essentially they validate each other. The validation criteria is that the object that goes in is the same as the one that comes out. There is indeed the possibility that what is already inside the system definition is the same as the newly created protocol object - if this is true, I still don't see the problem for several reasons:
> > 
> > * It can be very well a real-life scenario. A developer may attempt to apply a new Protocol to the Custom Device, and that Protocol could be indeed already set. The Set or Get Protocol VIs should work in this case as well as expected.
> > * Referring specifically to the test VIs - the content of the used System Definition file is KNOWN before the beginning of the tests: i.e. the protocol is set to a specific value, which is different from the value set by the first test VI. The initial protocol is AK RS-xxx and the first test VI is setting the VISA protocol.
> > * Each test saves the System Definition after applying the modification (after applying a protocol), which means that the next test is setting a different protocol.
> > * When developing the tests, I made sure to check the default values when creating a new IA Custom Device with a given protocol, so that when the "Set Protocol.vi" is running I can be certain that new and different values are applied each time.
> > 
> > Regarding the options you are mentioning:
> > 
> > 1. I run a "Get", and let's assume (even though, as I mentioned, the content of the SysDef before the beginning of the test is already known) that the found protocol object is the same as the one I am about to set - then what ? does it mean that the test fails ? I think that this idea is incomplete ...
> 
> It should fail if we expect something else there, as you already explained, we shouldn't have the same protocol object based on the current test setup.
> 
> > 1. It is a chicken and egg problem in this case - so we assume that the first pair of "Set" and "Get" is working, or does something, somehow to the System Definition, and the second pair is actually the one being tested, while the API used in both cases is the same ? What does it prove ? I think it would only increase the degree of uncertainty...
> 
> If we set totally different values for the protocol settings in the first "Set" and "Get" pair, then test that we have what we set, then do the the second pair of "Set" and "Get" and test for the new values, that for me is the biggest certainty that both nodes do what they should, and that we do not need to rely on the fact the system definition contains what was saved by the previous test,
> 
> > The best degree of certainty, in this case, in my opinion, is given by the fact that the content of the SysDef is known before the tests are running.
> 
> One other thing we may encounter, is for developers to run the same test two consecutive times on the development machine. Using this setup, when running for the second consecutive time the same test, this test does not really validates anything as we have the same protocol and settings already saved in the system definition.

Ok Paul sure. Let's summarize - I explained the current implementation of the API, the test setup (which is part of the test process itself) and the validation process, and I showed (I hope) that as it is, the scenario that you are describing will not occur. The initial state is known, and each test will run with the proper setup. Your argument is that if a developer runs the same test twice, then the second test will not count, because the protocol is already set (I assume that, by this logic, the first test, even though proper and successful does not count either ) - we are talking about automated testing, so tests are executing consecutively, without repetition, also I cannot account for everything that a developer might or might not do. 

My opinion is that other than code duplication and increased execution time, this modification will not achieve anything. But, let's do it ! :D .... at this point I think it's faster if I simply apply this modification.

**Comment by DStavilaNI** [comment]
> 
> 
> For all the submitted tests, we need to add a check beforehand that the current protocol settings in the Instrument Addon are different than the settings we add using the "Set Protocol" node.
> If the current protocol settings in the Instrument Addon are identical with the values we add in the test, the test will not identify errors in the "Set/Get Protocol" nodes.

Applied

**Review by phutanu — APPROVED** [review]

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
