### PR TITLE
Added wrappers for each protocol factory VI and for Get Protocol Type and updated the palette

### PR DESCRIPTION
**Pull request by csteavu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Created wrappers for all protocol factory VIs and for Get Protocol Type
- Created new Polymorphic VI from all new protocol factory VIs
- Added description to each VI and updated the Icons
-Updated the conpanes to match the design doc
-Updated the IACD Scripting Palette to match the design doc 

### Why should this Pull Request be merged?

IACD Scripting Palette does not match the design doc

### What testing has been done?

Built the CD . Further testing will be done when a feed is available

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
I would like all Factory wrappers to look like this one, but including each protocol name (TCP instead of PRTCL, for example):
image

**Comment by bogdanp-ni** [comment]
Please post a picture of how the palette looks :)

**Comment by bogdanp-ni** [comment]
Also, make sure that the polyVI will show the icon of the subVIs, not the generic icon.

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See my comments above.

**Comment by phutanu** [comment]
[Recommendation] should we name "Get Protocol Type.vi" -> "Get Protocol Type Wrapper.vi" just to be consistent with the Factory VIs?

**Review by phutanu — APPROVED** [review]
I'm ok with the change as long as you respond to my recommendation and you address @bogdanp-ni's comments from above.

**Comment by csteavu** [comment]
> [Recommendation] should we name "Get Protocol Type.vi" -> "Get Protocol Type Wrapper.vi" just to be consistent with the Factory VIs?

Renamed for consistency

**Comment by csteavu** [comment]
image

The Palette

**Comment by csteavu** [comment]
> I would like all Factory wrappers to look like this one, but including each protocol name (TCP instead of PRTCL, for example):
> image

Done.

Also addressed " the polyVI will show the icon of the subVIs, not the generic icon"

**Comment by bogdanp-ni** [comment]
> [Recommendation] should we name "Get Protocol Type.vi" -> "Get Protocol Type Wrapper.vi" just to be consistent with the Factory VIs?

I vote sticking with "Get Protocol Type", so that the name of the VI will match the label on the palette, like for all the other VIs. I find this more important than consistency with the factories.

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
Please revert the rename of "Get Protocol Type Wrapper".

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
