### PR TITLE
IA -> Add Command implementation

### PR DESCRIPTION
**Pull request by csteavu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Implementation of the Add Command.vi

- Implementation of the Test VIs

- Refactored subVI's used in Add Response so that they provide value to Add Command too

- Refactored the VIs used in Add Response so that they comply with the above mentioned subVI's

### Why should this Pull Request be merged?

Implements the "Add Command API" and corresponding tests

### What testing has been done?

- Implemented test VIs for the created API

- Testing on the local DEV machine has been done

### CODE REVIEW

**Comment by phutanu** [comment]
Add Command.vi -> Please make "Message Refnum In" and "Settings" inputs Required.
Command Settings.ctl -> Please change the name of "Pad" boolean to "Use Padding?".

**Comment by phutanu** [comment]
Resolve Linkaging.vi -> We need to add a check to make sure the "Command Format" is not empty. There is no use of creating a command with no command data.

**Comment by phutanu** [comment]
image

Please include the above code in a subVI called "Is Command or Response?.vi" or something simillar to that that will output a String (either "Command" or "Response") and a Boolean (True for Command, False for Response).
Replace the code with this new subVI in all the VIs that use this pattern.

**Comment by phutanu** [comment]
Linkages Node ID to GUID.vi -> you can replace the marked code with the new subVI "Is Command or Response.vi". This will make the diagram more readable and easy to understand.

image

**Comment by phutanu** [comment]
Command Linkages NodeID to GUID.vi -> is this VI used anywhere? I do not see it inside the "Add Command.vi"  nor inside the "Sripting API.lvlib". If it was submitted by accident, please remove it.

**Comment by phutanu** [comment]
Please update "Check Response&Variables Correspondence.vi" name to be more generic as it is used for both Command and Response. Choose a name that should reflect the action it does (It checks for correspondence between variables and linked channels). Please update the icon also.

image

**Comment by phutanu** [comment]
For the tests submitted:
- where the Command section does not exists, please add a check before adding the command to make sure the "Command" section does not exists where it should not. Just to validate our assumption. (The same is valid for the tests submitted for "Add Response").
- please add another test where the "Command" section exists in the Message. There you should check that the settings and linked channels you add override the initial settings present in the System Definition.
- please update the typos in the below label: "Linkages" , "Length"
image

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check my above comments.

**Comment by phutanu** [comment]
> Resolve Linkaging.vi -> We need to check that also the "Command Format" is not empty. There is no use of creating a command with no command data.
> 
> You can remove the GUID check and the case structure and refactor "Check for Empty Response.vi" to "Check for Empty Command/Response.vi"
> 
> image
> 
> Make also the "Command/Response Refnum In" a required input.

"Check for Empty Response.vi" needs to have the name changed to something like: "Check for Empty Command/Response.vi" as it is now checking for both the Command or Response. Please update also the icon to reflect this.

image

**Comment by phutanu** [comment]
> Linkages Node ID to GUID.vi -> you can replace the marked code with the new subVI "Is Command or Response.vi". This will make the diagram more readable and easy to understand.
> 
> image

For this VI we need to update the error string and code as well depending on the context where it is called (Command or Response). For the moment it will report the error always as coming from a "Response" even though it will be called for adding a Command also.

**Comment by phutanu** [comment]
> For the tests submitted:
> 
> * where the Command section does not exists, please add a check before adding the command to make sure the "Command" section does not exists where it should not. Just to validate our assumption. (The same check was added for the tests submitted for "Add Response").
> * please add another test where the "Command" section exists in the Message. There you should check that the settings and linked channels you add override the initial settings present in the System Definition.
> * please update the typos in the below label: "Linkages" , "Length"
>   image

Please add the same check highlighted below also to "test_Add Command_Use SysDef with Command with MetaData Channels.vi".

image

**Comment by phutanu** [comment]
Please also correct this small visual for "test_Add Command_Use SysDef With Only Custom Device.vi"

image

**Comment by phutanu** [comment]
Please revert the "Remove Target from Node Path.vi" as no change has been made to this VI.

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check the above active comments.

**Comment by bogdanp-ni** [comment]
Is Command or Response.vi -> currently, this VI is saying whether a refnum is a Command or not. I see two options:
- leave it as-is and rename it (don't mention "Response" at all): Validate Command Refnum, Is Command Refnum, etc. Maybe create a separate "Is Response Refnum" counterpart
- add validation in the Response case and throw an error if the refnum is neither of the two. Use an enum as the output of Command/Response/None

I prefer the first option.

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
I only left one comment that I would like to be addressed. Otherwise, I'm ok with the change.

**Comment by phutanu** [comment]
> Is Command or Response.vi -> currently, this VI is saying whether a refnum is a Command or not. I see two options:
> 
> * leave it as-is and rename it (don't mention "Response" at all): Validate Command Refnum, Is Command Refnum, etc. Maybe create a separate "Is Response Refnum" counterpart
> * add validation in the Response case and throw an error if the refnum is neither of the two. Use an enum as the output of Command/Response/None
> 
> I prefer the first option.

In the current implementation where this VI is used, it will get either a "Command Refnum In" or a "Response Refnum In". So that was the idea behind the implementation. But I do see that it may cause some false "Response" reporting if other refnum types will be connected at the "Command/Response Refnum in".

So I would also prefer the renaming option.

But if we think the current implementation can cause some issue in the future, we may add now an error throwing if the refnum is not identified as one of the two. This should be a small change.

**Review by bogdanp-ni — APPROVED** [review]
Regarding "Is Command Refnum", I believe the string output is now redundant - the same information can be extracted from the boolean "Is Command" and the "error out". I suggest you remove the string output altogether. As a general observation, I prefer not using string values as "status" indicators, when you have better alternatives (like enums, for example).

Otherwise, I'm ok with the change, as long as you address any remaining feedback from phutanu, he's been more involved in this PR from the beginning.

**Comment by phutanu** [comment]
> Regarding "Is Command Refnum", I believe the string output is now redundant - the same information can be extracted from the boolean "Is Command" and the "error out". I suggest you remove the string output altogether. As a general observation, I prefer not using string values as "status" indicators, when you have better alternatives (like enums, for example).
> 
> Otherwise, I'm ok with the change, as long as you address any remaining feedback from phutanu, he's been more involved in this PR from the beginning.

When the "Is Command Refnum.vi" does not report an error, the string that is given out is used for error reporting in the subsequent nodes to identify in what section there is an issue.

image

**Comment by phutanu** [comment]
Is Command Refnum.vi -> This error code needs to be updated to "5022", as the current value is already taken.
test_Add Command_Empty Command Format Error.vi -> Please update this also in the test.

image

**Review by phutanu — APPROVED** [review]

**Pull request merged**
