### PR TITLE
Implemented the functionality of the Get/Set Instrument Addon Name.vi

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This pull request implements the functionality of the Get/Set Instrument Addon Name.vi

### Why should this Pull Request be merged?

The functionality of the Get/Set Instrument Addon name.vi  was not implemented. 

### What testing has been done?

4 new unit tests were added covering two main and two corner cases. 
The IA was built locally and tested if the modifications to the Main Page.vi had any adverse effect on the IA product.

### CODE REVIEW

**Comment by DStavilaNI** [comment]
Error when open the project, with missing file:

image

Did anyone else see this ? :)

**Comment by DStavilaNI** [comment]
> 
> 
> Error when opening the project, with missing file:
> 
> image
> 
> Did anyone else see this ? :)

This issues comes for the length of the path that leads to this method and the  excessive length of the title of the SubVI: 

" test_Multiple Local Array Enumerated Channel Command-Response Messages using Trigger and Padding having Wait Sec Channel for Response.vi " . This makes the SubVI loadable from certain locations and not from others, which makes the project itself rather fragile.  For example, the SubVI loads if the project repo is situated in "C:\GitRepo" and does not load is the project repo is in "C:\Users\nitest\Downloads\"  ... it seems that we are reaching the length limit for subVI titles ....

**Comment by phutanu** [comment]
> Error when opening the project, with missing file:
> 
> image
> 
> Did anyone else see this ? :)

I am curious to see if it replicates on my test machine as the .lvproj , test class containing the test and that specific test have not been changed in a while.

**Comment by phutanu** [comment]
> > Error when opening the project, with missing file:
> > image
> > Did anyone else see this ? :)
> 
> This issues comes for the length of the path that leads to this method and the excessive length of the title of the SubVI:
> 
> " test_Multiple Local Array Enumerated Channel Command-Response Messages using Trigger and Padding having Wait Sec Channel for Response.vi " . This makes the SubVI loadable from certain locations and not from others, which makes the project itself rather fragile. For example, the SubVI loads if the project repo is situated in "C:\GitRepo" and does not load is the project repo is in "C:\Users\nitest\Downloads" ... it seems that we are reaching the length limit for subVI titles ....

Yep, that's why "C:\Dev\" is the perfect place for all of this. :)

**Comment by phutanu** [comment]
> > > Error when opening the project, with missing file:
> > > image
> > > Did anyone else see this ? :)
> > 
> > 
> > This issues comes for the length of the path that leads to this method and the excessive length of the title of the SubVI:
> > " test_Multiple Local Array Enumerated Channel Command-Response Messages using Trigger and Padding having Wait Sec Channel for Response.vi " . This makes the SubVI loadable from certain locations and not from others, which makes the project itself rather fragile. For example, the SubVI loads if the project repo is situated in "C:\GitRepo" and does not load is the project repo is in "C:\Users\nitest\Downloads" ... it seems that we are reaching the length limit for subVI titles ....
> 
> Yep, that's why "C:\Dev" is the perfect place for all of this. :)

It seems more like a LabVIEW problem that can cause issues on the Dev machines, as the paths on the ATS are also pretty long, but there the tests are loaded by cmd line call and not by opening the project. Also the builds worked fine until now.

**Comment by phutanu** [comment]
"Validate IA Name.vi": error -5005 was assigned in a previous PR, -5007 is available.

**Comment by phutanu** [comment]
Please add a check before "Set" and "Get" name in "test_Set Instrument Addon Name." to check for the initial name of the Instrument Addon and see that it is different than the one you set.

**Comment by bogdanp-ni** [comment]
Use "Instrument Addon" instead of "IA" in VI names.

**Comment by phutanu** [comment]
> "Validate IA Name.vi": error -5005 was assigned in a previous PR, -5007 is available.

Also do not forget to update this error code in the "test_Set Instrument Addon Name To Empty String.vi".

**Comment by phutanu** [comment]
Overall, I like how this PR looks. Clean and great attention to details. Very easy to do the review process. Thanks, Zoli! 👍

**Comment by phutanu** [comment]
Please also correct this label, from "Validate Instrument Addon Name Is Not In Use.vi". I know it is not a functional or significant change, but as this API will be public, we want it to be as professional and good as we can.

image

**Comment by phutanu** [comment]
> Please correct typos in "Get Instrument Addon Name" documentation:
> image

The same thing applies also for "Set Instrument Addon Name.vi"

**Comment by bogdanp-ni** [comment]
Remove comments unrelated to PR content.

**Review by bogdanp-ni — APPROVED** [review]

**Review by phutanu — APPROVED** [review]

**Pull request merged**
