### PR TITLE
IACD - "Add Response" test VI refactoring with Dynamic NodeID 

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Code refactoring for the "Add Response" Test VIs, given the Dynamic NodeID behavior discovered with the VS API.

- VI Renaming for some of the "Add Response" Test VIs, to maintain consistency across the test VIs

### Why should this Pull Request be merged?

- Fixes errors caused within the Add Respononse Test VIs by the dynamic NodeIDs generated during consecutive runs of the test VIs

### What testing has been done?

- Local testing has been done, both manually and using the "VI Tester" addon

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Check for Empty Command Or Response.vi -> please revert this file, because it has no changes (at least that's what LVCompare is reporting).

**Comment by bogdanp-ni** [comment]
[Recommend] For future reference when writing a test for errors and asserting with "passIfError" VI, the following construct should be used:
- wire the error out from the node expected to throw the error directly to passIfError's assertion terminal
- the regular error chain of the rest of the VI must be wired to passIfError's "error in" terminal 
This was, we separate the two error chains, since one is expected to have errors, and the other one is not.

image

**Review by bogdanp-ni — APPROVED** [review]
I'm ok with the change and will merge the code when the unchanged file is reverted and all merge conflicts are resolved.

**Comment by phutanu** [comment]
Generate Response Paramters.vi -> Typo in VI name ( Param _e_ ters )

**Review by phutanu — APPROVED** [review]
Except the small typo mentioned above, I'm ok with the change.

**Comment by DStavilaNI** [comment]
> 
> 
> [Recommend] For future reference when writing a test for errors and asserting with "passIfError" VI, the following construct should be used:
> 
>     * wire the error out from the node expected to throw the error directly to passIfError's assertion terminal
> 
>     * the regular error chain of the rest of the VI must be wired to passIfError's "error in" terminal
>       This was, we separate the two error chains, since one is expected to have errors, and the other one is not.
> 
> 
> image

The "Close Reference.vi" will execute normally even if there are errors on the input. Additionally, applying this recommendation would mean increasing the number of wires on the block diagram, but without a particular benefit to the execution flow ... if possible I would prefer to keep the current design

**Comment by DStavilaNI** [comment]
> 
> 
> Generate Response Paramters.vi -> Typo in VI name ( Param _e_ ters )

Done

**Comment by DStavilaNI** [comment]
> 
> 
> I'm ok with the change and will merge the code when the unchanged file is reverted and all merge conflicts are resolved.

Done

**Comment by bogdanp-ni** [comment]
> > [Recommend] For future reference when writing a test for errors and asserting with "passIfError" VI, the following construct should be used:
> > ```
> > * wire the error out from the node expected to throw the error directly to passIfError's assertion terminal
> > 
> > * the regular error chain of the rest of the VI must be wired to passIfError's "error in" terminal
> >   This was, we separate the two error chains, since one is expected to have errors, and the other one is not.
> > ```
> > 
> > 
> > image
> 
> The "Close Reference.vi" will execute normally even if there are errors on the input. Additionally, applying this recommendation would mean increasing the number of wires on the block diagram, but without a particular benefit to the execution flow ... if possible I would prefer to keep the current design

Sure, no problem, this was solely a recommendation for the current PR. But I would like for us to use this pattern in the future and here's why:
- JKI's node "passIfError" has two different error inputs exactly to separate the "I expect this error to be present on this wire" from "I got an error in the test flow". Otherwise, it would just have one error input
- it would be a lot cleaner to separate "test conditions" (expected error on a particular wire) from "infrastructure" (the test VI's error chain) - this is something that NI's testing guidelines recommend and a big benefit on the execution flow
- if you propagate the "expected error" through the error chain, at the end it's harder to check that the error source is the expected VI (and not some other VI that got executed afterwards of even before)
- there would be no need to use "Clear Errors". In your implementation, you might be clearing an infrastructure error and yes, the test will still fail, but it will fail with the fact that the expected code doesn't match the actual error code, when in fact it should fail with "error received where it shouldn't have been any error"

I did not know that Close Reference executes regardless  of the error input, thanks for sharing that 👍

**Comment by bogdanp-ni** [comment]
I see the refactor done on reference closing is not here anymore. Why is that?

**Pull request merged**
