### PR TITLE
IA - Implementation of the "Create Instrument Addon from Configuration File.vi"  scripting API

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Completed the Create Instrument Addon from Configuration File.vi part of the API
- Created a test case for the Create Instrument Addon from Configuration File.vi API
- Created a template Icon for the Instrument Addon Scripting API.lvlib ... to be modified if necessary

### Why should this Pull Request be merged?

Implements part of the Instrument Addon Scripting API -> creating an Instrument Addon CD from configuration file. Adds a default Icon template for the Instrument Addon Scripting API.lvlib

### What testing has been done?

- Created a test case for the Create Instrument Addon from Configuration File.vi API. Tested locally

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
If the icon was modified for all those VI's, I'd prefer that change to be in a separate PR.

**Comment by bogdanp-ni** [comment]
> > If the icon was modified for all those VI's, I'd prefer that change to be in a separate PR.
> 
> Sure

Did you update the files? I'm still seeing 57 changes, for some reason.

**Review by phutanu — COMMENTED** [review]
Also please revert the changes to:
- test_Source Separated.vi
- test_Connector Pane.vi
- Instrument Addon Specific System Tests.lvclass
- Instrument Addon Host API Tests.lvclass
- Error System Tests/test_Basic Deployment.vi
- Instrument Addon Error System Tests.lvclass
- Common System Tests/test_Basic Deployment.vi
- Instrument Addon Common System Tests.lvclass
- System Tests/Assets/SubVIs/Update TCP IP nodes with Test Machine IP.vi
- System Tests/Assets/SubVIs/Update Sys Def by Target type.vi

**Comment by DStavilaNI** [comment]
Hey Guys. Thank you for your feedback. I think reverting will take to much time in this case - some of the changes were made across multiple commits. I will close this PR and create a new one.

**Comment by DStavilaNI** [comment]
It makes more sense to start from the original project, and simply add the new files.

**Pull request closed without merging**
