### PR TITLE
Added call chain for errors

### PR DESCRIPTION
**Pull request by csteavu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Added call chain for errors

### Why should this Pull Request be merged?

To show call chain in errors reported in the API. 

### What testing has been done?

N/A

### CODE REVIEW

**Comment by phutanu** [comment]
Please add the error chain also for error 5014 in VI: "Linkages NodeID to GUID.vi"

image

**Review by phutanu — APPROVED** [review]
Except the additional error chain, mentioned in the previous comment, that still needs to be added, I'm ok with this PR.

**Review by bogdanp-ni — APPROVED** [review]

**Comment by csteavu** [comment]
> Please add the error chain also for error 5014 in VI: "Linkages NodeID to GUID.vi"
> 
> image

Fixed

**Comment by csteavu** [comment]
image
image
Diffbot is down, postet snips instead

**Review by phutanu — APPROVED** [review]

**Pull request merged**
