### PR TITLE
Updated the error messages 

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

The error messages thrown by the scripting API were updated. (corrected).
Also, where error ring was used it was replaced by "Error Cluster From Error Code.vi" node in order to get a complete call stack.

### Why should this Pull Request be merged?

The current error codes contain grammatically errors and the way they are thrown are not uniform.

### What testing has been done?

Verified that the modified VI did not got broken during the update process.

### CODE REVIEW

**Comment by phutanu** [comment]
This error string from "Get Protocol.vi" needs to be updated also.

image

**Comment by phutanu** [comment]
Please update also this error code inside "Set Protocol.vi":

image

**Comment by phutanu** [comment]
Please include the call chain for this error, and also please cleanup the marked wires.

image

**Comment by phutanu** [comment]
Please include the call chain for this error:

image

**Comment by phutanu** [comment]
Please include call chain for this error:

image

**Comment by phutanu** [comment]
I noticed that "Validate Name in Section.vi" is used to validate Channel names (Single or Array) and not sections as the name may imply. So to avoid any confusion, my suggestion would be to rename it to something like "Validate Channel Name" and the errors 5023 and 5024 should be updated to something similar with below, as the current error strings are also a bit confusing for the users.

5023 = A name has not been specified for this channel. Assign a name.
5024 = The name "NAME" is already in use. Assign a different channel name.

Can you please, also replace the highlighted code with "Error Cluster from Error Code.vi" in order to have also the call chain?

image

**Comment by phutanu** [comment]
Please include call chain for the below error:
image

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check my above comments.

**Comment by bogdanp-ni** [comment]
"Call chain" here:

image

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
Just the one comment above.

**Review by bogdanp-ni — APPROVED** [review]

**Comment by phutanu** [comment]
This error will be always thrown when a name will be assigned.
Please add a "select" or case structure to throw the error only when the name already exists.

image

**Review by phutanu — CHANGES_REQUESTED** [review]
Please address the above comment and this PR is good to go.

**Comment by zszilagy** [comment]
> This error will be always thrown when a name will be assigned.
> Please add a "select" or case structure to throw the error only when the name already exists.
> 
> image

Fixed as requested.

**Review by phutanu — APPROVED** [review]

**Pull request merged**
