### PR TITLE
Refactored the VI so it doesn't assign automatically a name to the message group when the user specifies an empty string as message group name.

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This VM updates the **Create Message Group.vi** so it no longer accepts empty string as an input.

### Why should this Pull Request be merged?

The current implementation is incorrect because it automatically assigns a generic name to the message group instead of notifying the user about the error which was made while writing the code.

### What testing has been done?

n/a

### CODE REVIEW

**Comment by phutanu** [comment]
It the "Label Out" terminal of the "Get Next Unique Label" is not the same as the "message group name" input terminal we need to report another error and do not create the message group section.
So we should use the "Get Next Unique Label" just as a check that the "message group name" input is unique.

image

**Review by phutanu — CHANGES_REQUESTED** [review]
Please address my above comment.

**Review by bogdanp-ni — APPROVED** [review]
Approved and ok to submit when pending comments are addressed.

**Comment by zszilagy** [comment]
> It the "Label Out" terminal of the "Get Next Unique Label" is not the same as the "message group name" input terminal we need to report another error and do not create the message group section.
> So we should use the "Get Next Unique Label" just as a check that the "message group name" input is unique.
> 
> image

Implemented!

**Review by phutanu — APPROVED** [review]

**Pull request merged**
