### PR TITLE
IA export config

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Implemented the Export Instrument Add-on Configuration.vi
- Implemented unit tests for the Export Instrument Addon Configuration.vi
- Modified the ExportConfigurationToFile.vi with the new API - Export Instrument Add-on Configuration.vi

### Why should this Pull Request be merged?

- Implemented the Export Instrument Add-on Configuration.vi

### What testing has been done?

- Implemented unit tests for the Export Instrument Add-on Configuration.vi

### CODE REVIEW

**Review by phutanu — COMMENTED** [review]
Please revert the following changes as I assume they were not intended:
- System Tests/Assets/SubVIs/Update Sys Def by Target type.vi
- System Tests/Assets/SubVIs/Update TCP IP nodes with Test Machine IP.vi
- Tests/Unit Tests/Instrument Addon/test_Connector Pane.vi
- Tests/Unit Tests/Instrument Addon/test_Source Separated.vi

- System Tests/Common System Tests/test_Basic Deployment.vi
- System Tests/Error System Tests/test_Basic Deployment.vi

- System Tests/Common System Tests/Instrument Addon Common System Tests.lvclass
- System Tests/Error System Tests/Instrument Addon Error System Tests.lvclass
- System Tests/Error System Tests/test_Basic Deployment.vi
- System Tests/Host API Tests/Instrument Addon Host API Tests.lvclass
- System Tests/Specific System Tests/Instrument Addon Specific System Tests.lvclass

**Comment by DStavilaNI** [comment]
> 
> 
> Please revert the following changes as I assume they were not intended:
> 
>     * System Tests/Assets/SubVIs/Update Sys Def by Target type.vi
> 
>     * System Tests/Assets/SubVIs/Update TCP IP nodes with Test Machine IP.vi
> 
>     * Tests/Unit Tests/Instrument Addon/test_Connector Pane.vi
> 
>     * Tests/Unit Tests/Instrument Addon/test_Source Separated.vi
> 
>     * System Tests/Common System Tests/test_Basic Deployment.vi
> 
>     * System Tests/Error System Tests/test_Basic Deployment.vi
> 
>     * System Tests/Common System Tests/Instrument Addon Common System Tests.lvclass
> 
>     * System Tests/Error System Tests/Instrument Addon Error System Tests.lvclass
> 
>     * System Tests/Error System Tests/test_Basic Deployment.vi
> 
>     * System Tests/Host API Tests/Instrument Addon Host API Tests.lvclass
> 
>     * System Tests/Specific System Tests/Instrument Addon Specific System Tests.lvclass

Done

**Comment by phutanu** [comment]
"Instrument Addon Refnum in" and "Instrument Addon Refnum out" ports for "Export Instrument Addon Configuration.vi" need to be typedefs.

**Comment by bogdanp-ni** [comment]
In ExportConfigurationToFile, I see there already is a call to Export Custom Device Configuration, why can't we further use that one?

image

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
Please see my comment on reusing ImportExport.lvlib:Export Custom Device Configuration

**Comment by DStavilaNI** [comment]
> 
> 
> "Instrument Addon Refnum in" and "Instrument Addon Refnum out" ports for "Export Instrument Addon Configuration.vi" need to be typedefs.

Why do they have to be typeDefs ?  It's a simple U64 dataType. The Advanced System Defintion API does not use TypeDefs, nor TypeDefs are used consistently even by the .NET API for VeriStand. I was using U64 TypeDefs in some of my implementations, but I did not see consistency through other API.  

It's not a typeDef in the original ExportConfigurationToFile.vi either.

**Comment by DStavilaNI** [comment]
> 
> 
> Please see my comment on reusing ImportExport.lvlib:Export Custom Device Configuration

Sure ... did you happen to check the implementation of the Export Custom Device Configuration.vi ?

> 
> 
> Please see my comment on reusing ImportExport.lvlib:Export Custom Device Configuration

If you look inside the SubVI you are pointing at, you will see this:

image

What that means, is that every-time it is called, it will display a dialog window, for the user to select the location and a name for a .dat file. It works totally fine as a RTM action, which expects an user input, but I am not sure this is the desired behavior when building an API - my idea was that you have a path input which contains the location at which you want to save the config file. If that path would be empty (intentionally), then this is when you display the dialog window for the user.

Modifying the original ImportExport library is not an option either.

**Comment by bogdanp-ni** [comment]
> > "Instrument Addon Refnum in" and "Instrument Addon Refnum out" ports for "Export Instrument Addon Configuration.vi" need to be typedefs.
> 
> Why do they have to be typeDefs ? It's a simple U64 dataType. The Advanced System Defintion API does not use TypeDefs, nor TypeDefs are used consistently even by the .NET API for VeriStand. I was using U64 TypeDefs in some of my implementations, but I did not see consistency through other API.
> 
> It's not a typeDef in the original ExportConfigurationToFile.vi either.

The use of typedefs for references is documented in the spec and was agreed upon during the review process. We'll have to stick to that.

**Comment by DStavilaNI** [comment]
> 
> 
> > Please see my comment on reusing ImportExport.lvlib:Export Custom Device Configuration
> 
> Sure ... did you happen to check the implementation of the Export Custom Device Configuration.vi ?
> 
> > Please see my comment on reusing ImportExport.lvlib:Export Custom Device Configuration
> 
> If you look inside the SubVI you are pointing at, you will see this:
> 
> image
> 
> What that means, is that every-time it is called, it will display a dialog window, for the user to select the location and a name for a .dat file. It works totally fine as a RTM action, which expects an user input, but I am not sure this is the desired behavior when building an API - my idea was that you have a path input which contains the location at which you want to save the config file. If that path would be empty (intentionally), then this is when you display the dialog window for the user.
> 
> Modifying the original ImportExport library is not an option either.

Actually, my bad here - I think that the package version that I have received originally, for this toolkit, is obsolete. The block diagram for the VI that you are displaying corresponds to a more recent version. 

Still, my implementation is similar to what is there + I am doing additional checking for the path and the ".dat" file extension. Furthermore, the file path in my case is a required input, and an error is being thrown if the previous two conditions are not met. If I am to reuse the previous vi, it would mean to create a wrapper around it and do the same condition checking ... I don't think it makes sense, since as it is, it's already implemented.

**Comment by bogdanp-ni** [comment]
> > Please see my comment on reusing ImportExport.lvlib:Export Custom Device Configuration
> 
> Sure ... did you happen to check the implementation of the Export Custom Device Configuration.vi ?
> 
> > Please see my comment on reusing ImportExport.lvlib:Export Custom Device Configuration
> 
> If you look inside the SubVI you are pointing at, you will see this:
> 
> image
> 
> What that means, is that every-time it is called, it will display a dialog window, for the user to select the location and a name for a .dat file. It works totally fine as a RTM action, which expects an user input, but I am not sure this is the desired behavior when building an API - my idea was that you have a path input which contains the location at which you want to save the config file. If that path would be empty (intentionally), then this is when you display the dialog window for the user.
> 
> Modifying the original ImportExport library is not an option either.

Thanks for the explanation, I agree with you on not reusing that node.

Regarding how we're achieving the functionality:
- for the UI use-case, we need to have the same pop-up appear (which I see you already did)
- for the scripting use-case, an error must be thrown when the path is empty or invalid (like we did for Create from Config)

This means that the pop-up dialog code must be  ExportConfigurationToFile (or in a separate subVI) and not in the scripting API. This would also ensure a better separation of responsibilities. Also, the error case will not be reachable from the UI, since the dialog will always output a valid path (the error is useful only when scripting).

**Comment by DStavilaNI** [comment]
> 
> 
> > > Please see my comment on reusing ImportExport.lvlib:Export Custom Device Configuration
> > 
> > 
> > Sure ... did you happen to check the implementation of the Export Custom Device Configuration.vi ?
> > > Please see my comment on reusing ImportExport.lvlib:Export Custom Device Configuration
> > 
> > 
> > If you look inside the SubVI you are pointing at, you will see this:
> > image
> > What that means, is that every-time it is called, it will display a dialog window, for the user to select the location and a name for a .dat file. It works totally fine as a RTM action, which expects an user input, but I am not sure this is the desired behavior when building an API - my idea was that you have a path input which contains the location at which you want to save the config file. If that path would be empty (intentionally), then this is when you display the dialog window for the user.
> > Modifying the original ImportExport library is not an option either.
> 
> Thanks for the explanation, I agree with you on not reusing that node.
> 
> Regarding how we're achieving the functionality:
> 
>     * for the UI use-case, we need to have the same pop-up appear (which I see you already did)
> 
>     * for the scripting use-case, an error must be thrown when the path is empty or invalid (like we did for Create from Config)
> 
> 
> This means that the pop-up dialog code must be ExportConfigurationToFile (or in a separate subVI) and not in the scripting API. This would also ensure a better separation of responsibilities. Also, the error case will not be reachable from the UI, since the dialog will always output a valid path (the error is useful only when scripting).

I agree with moving the dialog display code outside.

**Comment by DStavilaNI** [comment]
> 
> 
> > > "Instrument Addon Refnum in" and "Instrument Addon Refnum out" ports for "Export Instrument Addon Configuration.vi" need to be typedefs.
> > 
> > 
> > Why do they have to be typeDefs ? It's a simple U64 dataType. The Advanced System Defintion API does not use TypeDefs, nor TypeDefs are used consistently even by the .NET API for VeriStand. I was using U64 TypeDefs in some of my implementations, but I did not see consistency through other API.
> > It's not a typeDef in the original ExportConfigurationToFile.vi either.
> 
> The use of typedefs for references is documented in the spec and was agreed upon during the review process. We'll have to stick to that.

Ok then.

**Comment by DStavilaNI** [comment]
> 
> 
> Please see my comment on reusing ImportExport.lvlib:Export Custom Device Configuration

Done

**Review by phutanu — APPROVED** [review]

**Comment by bogdanp-ni** [comment]
-5003 was already used in a previous PR, for this CD. -5005 is available

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
