### PR TITLE
Refactor Create Array Channels

### PR DESCRIPTION
**Pull request by phutanu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Refactors the Create Data and MetaData Channels Scripting nodes to use only "Add Array Data Channels.vi" for both Data and MetaData array elements creation as the functionality is very similar.

### Why should this Pull Request be merged?

- To have only one VI that is creating both Data and MetaData Array Elements and not two similar implementations.

### What testing has been done?

- All build specifications under the windows target run successfully.
- All Unit and System Level tests were run locally under windows target.
- Manual testing done in VeriStand 2018 to check that nothing break.

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Could you get rid of this coercion dot?

image

**Comment by bogdanp-ni** [comment]
Is this change modifying the public API?

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See above.

**Comment by phutanu** [comment]
> Is this change modifying the public API?

No, it is not

> Could you get rid of this coercion dot?
> 
> image

Fixed.

**Comment by phutanu** [comment]
> Is this change modifying the public API?

No, it is not. No change was made to the top scripting nodes. They look and function as before.

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
