### PR TITLE
Added VI which validates the PCL Decimation value set by the user in scripting context

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Validates the value set by the user as PCL Decimation. In case if the value is lower than 0 and error is thrown. (Error 5004)

### Why should this Pull Request be merged?

Currently the user is able to set the PCL Decimation value to 0, however, in the original IA behavior the value is coerced to 1. As not notifying the user in scripting environment about an incorrect input value is a bad practice, this functionality must be added.

### What testing has been done?
Created and run unit test which validates this new functionality. Built the IA locally and verified it this implementation does not affect the existing functionality negatively.

### CODE REVIEW

**Comment by phutanu** [comment]
Please adjust the "test_Set PCL Decimation to 0.vi" icon to better reflect the test scope. Maybe just removing "GET/" would be enough.

**Comment by bogdanp-ni** [comment]
The validation of the IA CD refnum must happen _before_ the validation of the PCL decimation value, because you are using the refnum as an input to the validation subVI (even if it's not used, at the moment).

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See my previous comment: The validation of the IA CD refnum must happen before the validation of the PCL decimation value, because you are using the refnum as an input to the validation subVI (even if it's not used, at the moment).

**Comment by zszilagy** [comment]
> See my previous comment: The validation of the IA CD refnum must happen before the validation of the PCL decimation value, because you are using the refnum as an input to the validation subVI (even if it's not used, at the moment).

Changed as requested!

**Comment by zszilagy** [comment]
> Please adjust the "test_Set PCL Decimation to 0.vi" icon to better reflect the test scope. Maybe just removing "GET/" would be enough.

Changed as requested.

**Review by phutanu — APPROVED** [review]

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
