### PR TITLE
Added scripting logic to Delete Instrument Addon

### PR DESCRIPTION
**Pull request by csteavu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Added scripting logic to Delete Instrument Addon
Closed references in test_Create Message Group_Message Group created with desired Name.vi
Please note that there is no refactor needed , as the Instrument Addon Custom Device removal is not handled by VI's within the custom device API

### Why should this Pull Request be merged?

There was no scripting logic to Delete Instrument Addon;
test_Create Message Group_Message Group created with desired Name.vi had references that were not closed.

### What testing has been done?

Created and ran tests with VI Tester

### CODE REVIEW

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
test_Create Message Group_Message Group created with desired Name.vi -> this one doesn't seem to belong in this PR.

**Comment by phutanu** [comment]
For "Delete Instrument Addon.vi" please:
- make the "Instrument Addon Refnum" a Required input.
- add documentation.

**Comment by phutanu** [comment]
For "test_Delete Instrument Addon.vi" please:
- Add a check before Deletion to make sure there is an Instrument Addon.
- Change the Icon text to better reflect the test scope.

**Comment by phutanu** [comment]
Also, please add another test in which you have more than one Instrument Addons in which it will be checked the node deletes only the Refnum specified as input.

**Comment by phutanu** [comment]
I know it is a minor change, but please change this label from "test_Delete Instrument Addon" into something like: "Check that the Correct Instrument Addon remains after deletion."
label

**Comment by phutanu** [comment]
It seems that no functional or visible change has been made to "Find Instrument Addon Custom Device.vi". If that is the case, I would revert that change.

**Review by phutanu — APPROVED** [review]

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
