### PR TITLE
IA Palette Implementation

### PR DESCRIPTION
**Pull request by DStavilaNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Implemented the palette files 
- Updated the API library
- Updated corresponding Scripting API build specs

### Why should this Pull Request be merged?

- Implemented and added the palette files

### What testing has been done?

- Manual testing has been done on the local/dev PC, by moving manually the files to the appropriate LV Directories. 

Steps: 
1. Run the Scripting API build spec. 
2. From the generated files - copy the content of the "Scripting API" folder to "vi.lib\addons\VeriStand Custom Device Scripting APIs\Instrument Addon"
3. Enjoy :)

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Please change the palettes so that they match the version documented in the spec, since this one was agreed upon with the customers (including the nodes names visible on the palettes):

image

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See my comment on palette structure and node names on palette.

**Comment by DStavilaNI** [comment]
> 
> 
> Please change the palettes so that they match the version documented in the spec, since this one was agreed upon with the customers (including the nodes names visible on the palettes):
> 
> image

Changed

**Review by phutanu — CHANGES_REQUESTED** [review]
All VI names in the palette should not contain ".vi" in the naming (short name).

image

**Comment by phutanu** [comment]
Mentioning [Instrument Addon Classes PR#40](https://github.com/ni/niveristand-instrument-addon-classes/pull/40) as the changes there can be merged only after the current PR gets approved and merged.

**Review by bogdanp-ni — APPROVED** [review]
I am ok with the change, as long as Paul's comments will be addressed.

I have one minor point - for these two nodes, please add "Channel" at the end:
image

**Comment by DStavilaNI** [comment]
> 
> 
> I am ok with the change, as long as Paul's comments will be addressed.
> 
> I have one minor point - for these two nodes, please add "Channel" at the end:
> image

These names are shortened automatically by Labview to fit in the label field ... the name itself contains the word "channel"

**Review by phutanu — APPROVED** [review]

**Pull request merged**
