### PR TITLE
Fixed the issue where no Global Metadata Channels section was created under the IA CD (scripting only)

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR fixes the bug related to "Global MetaData Channels" section that was missing and adds a unit test to validate the added functionality. The bug refers to the behavior where no Global Metadata Section is created when creating a new Instrument Addon Custom device using the scripting API node.

### Why should this Pull Request be merged?

No Global Metadata Channels section is created currently when using the Scripting API.

### What testing has been done?

Built the Configuration Release and Scripting API build specifications.
Wrote a new unit test to test the functionality.

### CODE REVIEW

**Review by phutanu — APPROVED** [review]
Please rename the newly added test from:
"test_Create Global MetaData Channel_No existing IA CD.vi" to: 
"test_Create Global MetaData Channel_after adding a IA CD.vi"

And maybe add a label on the test block diagram to state the reason for this test. Or why we want to test this.

Please submit also the "Instrument Addon Scripting API Channels Unit Tests.lvclass" library that should contains the new test.

Otherwise this looks ok from my side.

**Comment by bogdanp-ni** [comment]
Please use the constant named "Global MetaData Channels" (just like with the GUID) instead of a plain string:

image

**Comment by bogdanp-ni** [comment]
[Recommend] Is there a reason why you did not use the same approach from Initialize VI.vi?

image

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See comments above. And there are some open issues pointed out by phutanu, as well.

**Comment by zszilagy** [comment]
> Please rename the newly added test from:
> "test_Create Global MetaData Channel_No existing IA CD.vi" to:
> "test_Create Global MetaData Channel_after adding a IA CD.vi"
> 
> And maybe add a label on the test block diagram to state the reason for this test. Or why we want to test this.
> 
> Please submit also the "Instrument Addon Scripting API Channels Unit Tests.lvclass" library that should contains the new test.
> 
> Otherwise this looks ok from my side.

Fixed!

**Comment by zszilagy** [comment]
> Please use the constant named "Global MetaData Channels" (just like with the GUID) instead of a plain string:
> 
> image

Fixed.

**Comment by zszilagy** [comment]
> [Recommend] Is there a reason why you did not use the same approach from Initialize VI.vi?
> 
> image

I used the .NET API as to stay consistent in the subvi. Using the same approach as the Initialize.vi does not add any value to the code.

**Comment by zszilagy** [comment]
> > Please use the constant named "Global MetaData Channels" (just like with the GUID) instead of a plain string:
> > image
> 
> Fixed.

image

**Comment by zszilagy** [comment]
> > Please rename the newly added test from:
> > "test_Create Global MetaData Channel_No existing IA CD.vi" to:
> > "test_Create Global MetaData Channel_after adding a IA CD.vi"
> > And maybe add a label on the test block diagram to state the reason for this test. Or why we want to test this.
> > Please submit also the "Instrument Addon Scripting API Channels Unit Tests.lvclass" library that should contains the new test.
> > Otherwise this looks ok from my side.
> 
> Fixed!

image

image

**Review by phutanu — APPROVED** [review]

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
