### PR TITLE
Add typedefs required for Metadata and Data Channels creation

### PR DESCRIPTION
**Pull request by bogdanp-ni**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds common typedefs required for "Create (Global) MetaData Channel" and "Create Data Channel" scripting API nodes.

### Why should this Pull Request be merged?

To unblock zszilagy, who is working on "Create Data Channel".

### What testing has been done?

N/A

### CODE REVIEW

**Review by phutanu — COMMENTED** [review]
Also these 2 files need to be reverted:
- System Tests/Common System Tests/Instrument Addon System Tests.lvclass
- Instrument Addon Scripting API Custom Device Unit Tests/Instrument Addon Scripting API Custom Device Unit Tests.lvclass

**Comment by bogdanp-ni** [comment]
> Also these 2 files need to be reverted:
> 
> * System Tests/Common System Tests/Instrument Addon System Tests.lvclass
> * Instrument Addon Scripting API Custom Device Unit Tests/Instrument Addon Scripting API Custom Device Unit Tests.lvclass

Done, fixed!

**Review by phutanu — APPROVED** [review]

**Comment by phutanu** [comment]
Does the change to the .lvproj file is intended/required?

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check my above comment regarding the change to the .lvproj file.

**Comment by bogdanp-ni** [comment]
> Please check my above comment regarding the change to the .lvproj file.

Fixed!

**Review by phutanu — APPROVED** [review]

**Pull request merged**
