### PR TITLE
Fix MetaData channel creation

### PR DESCRIPTION
**Pull request by bogdanp-ni**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Fix Add MTD Channel and Add MTD Array from UI. Fix associated tests.

### Why should this Pull Request be merged?

Fixes feature bug.

### What testing has been done?

Manual testing on IA CD. Ran relevant automated tests.

### CODE REVIEW

**Comment by phutanu** [comment]
Add New MetaData Channel.vi -> It seems like there is a glitch in Diff Bot or all the Block Diagram code was removed from this RTM Menu.

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check my above comment. It seems like a Diff Bot glitch but let's make sure.

**Review by phutanu — APPROVED** [review]
Please check my above comment. It seems like a Diff Bot glitch but let's make sure.
Otherwise I'm ok with the change.

**Comment by bogdanp-ni** [comment]
> Add New MetaData Channel.vi -> It seems like there is a glitch in Diff Bot because the description below states the apparent correct changes. Can you double check that the VI is in a good running state? And maybe add a Block Diagram snip here?

Sure, here it is:

image

**Review by phutanu — APPROVED** [review]

**Pull request merged**
