### PR TITLE
Refactored the "Add Response.vi" to two components

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Refactored the "Add Response.vi" to two components the same way as Add Command.vi was refactored. The following components were created: Create Response.vi and Configure Response.vi (polymorphic vi).

All the "Response" related unit tests were updated to use the new implementation. 
All the tests of which name started with "test_Add Response..."  were renamed accordingly to the action they perform:
- test_Configure Response... -> this means that the system definition which is used in the test already contains a response.
- test_Create Response...-> this means that the system definition which is used in the test does not contain a response.

The new VIs are aligned with the latest HLD document.
The documentation of the VIs were also updated to match the current implementation.

### Why should this Pull Request be merged?

The current implementation is more decentralized than the previous one. This pattern was applied on the old "Add Command.vi" (now Create Command.vi and Configure Command.vi). 

### What testing has been done?

After the modifications were applied (on the VIs and also on the tests) every test was run locally to make sure that the functionality did not change.

Added two new unit tests.

### CODE REVIEW

**Comment by phutanu** [comment]
Create Message Response.vi -> This VI needs also to be updated to be similar with the Command implementation.
- Name should be change to: "Add Message Response"
- Icon also needs to be updated.

**Review by phutanu — CHANGES_REQUESTED** [review]
Create Message Response.vi -> This VI needs also to be changed to be similar with the Command implementation.
- Name should be change to: "Add Message Response"
- Icon also needs to be updated.

**Review by bogdanp-ni — APPROVED** [review]
Approved, as long as you address pending comments.

**Comment by zszilagy** [comment]
> Create Message Response.vi -> This VI needs also to be changed to be similar with the Command implementation.
> 
> * Name should be change to: "Add Message Response"
> * Icon also needs to be updated.

Fixed as requested.

**Comment by phutanu** [comment]
@zszilagy the diff bot did not show anything for "SubVIs/Add Message Response.vi". Can you please add a snip here?

**Comment by zszilagy** [comment]
> @zszilagy the diff bot did not show anything for "SubVIs/Add Message Response.vi". Can you please add a snip here?

image

image

here it is. The library was not saved during the previous commit that's why the file didn't show up in the diff. If you wan you can wait for next diff or use the attached screenshots.

**Review by phutanu — APPROVED** [review]

**Pull request merged**
