### PR TITLE
Implemented the functionality of the Create Data Channel polymorphic VI

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds the functionality of the Create Data Channel polymorphic VI. Also a few VIs were refactored of the Instrument Addon Custom Device in order to re-use code from the scripting API.

### Why should this Pull Request be merged?

The functionality of the Create Data Channel polymorphic VI is missing from the Scriptin API.

### What testing has been done?

Created automated tests to validate the functionality of the newly implemented VIs. All the tests passed locally.
Built the IA CD custom device locally and did freeform testing the System Explorer.

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Set Channel Value Table.vi -> this VI is part of the Shared lvlib, but on disk it resides in the Scripting API folder.

**Comment by phutanu** [comment]
Create Message Response.vi -> This VI needs some cleanup on the Block Diagram.

image

**Comment by phutanu** [comment]
Get or Create Response.vi -> Please correct the name of "Message Refnum In **in**" input, by removing the bolded part.
Also, please adjust the output nodes names to make all of them visible.

image

**Comment by phutanu** [comment]
Channel or Section Name Valid.vi -> Please rename this VI to: "Validate Channel or Section Name.vi" in order to strive for consistency with the other validate nodes and give a unitary aspect to our API.

**Comment by phutanu** [comment]
Create Data Channel - Array - Type Cast.vi -> The enum marked below should have the value "Type Cast".

image

**Comment by phutanu** [comment]
For all "Create Data Channels" of Array Type. I find the current Documentation wording a bit confusing.

I would adapt it to something similar to the below:

_Creates a new Data Channel with the following configuration:
Data Type: Array
Channel Type: {enum, format, etc.}

It also creates all the channel elements specified in the "Elements" array from the "Settings" input.

Input:
Message Refnum In: reference to the "Response" message section.
Name: represents the desired name of the Data Channel
Settings: represents the settings applied as well as the settings for each element which will be added to the Data Channel

Output:
Message Refnum Out: reference to the "Response" message section used as input.
Channel Refnum: reference to the newly created Data Channel section._

**Comment by phutanu** [comment]
For all "Create Data Channels" please correct this typo in the VI documentation (correct: "Refnum"):

image

**Comment by phutanu** [comment]
Create Data Channel - Array - Comparison.vi -> The marked enum should have the value "Comparison".

image

**Comment by phutanu** [comment]
Data Parameters FG.vi -> the below changed settings need to be reverted.

image

**Comment by phutanu** [comment]
Validate Channel or Array Name.vi -> The specified error codes are already taken. Please use the next incremental error codes available in the "Instrument Addon Scripting Error Codes" document and update the info there.

image

**Comment by phutanu** [comment]
> Validate Channel or Array Name.vi -> The specified error codes are already taken. Please use the next incremental error codes available in the "Instrument Addon Scripting Error Codes" document and update the info there.
> 
> image

Is this VI used somewhere? I am having a hard time finding the a caller VI for it.

**Comment by phutanu** [comment]
We need to add an additional check in all the unit tests to check the type of the Channels added.
The current unit tests failed to identify the wrong enum value for "Create Data Channel - Array - Comparison.vi" and "Create Data Channel - Array - Type Cast.vi"

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check my above comments.

**Comment by zszilagy** [comment]
> Create Message Response.vi -> This VI needs some cleanup on the Block Diagram.
> 
> image

Fixed as requested.

**Comment by zszilagy** [comment]
> Get or Create Response.vi -> Please correct the name of "Message Refnum In **in**" input, by removing the bolded part.
> Also, please adjust the output nodes names to make all of them visible.
> 
> image

Fixed as requested.

**Comment by zszilagy** [comment]
> Channel or Section Name Valid.vi -> Please rename this VI to: "Validate Channel or Section Name.vi" in order to strive for consistency with the other validate nodes and give a unitary aspect to our API.
> 
> Also, I would prefer to report the error right from inside the validate node, and remove the "Name Valid?" output as this info will become redundant with the info from the error wire.
> 
> You then, can remove the outer case structure from "Create Data Channel Element.vi" as the error will be passed through and reported out, or replace that case with an error case structure. As you prefer.
> 
> image
> 
> Also, we can discard the "Throw Invalid Name Error.vi" and just use the code inside the "Validate Channel or Section Name.vi".
> 
> Also, refactor the "Add Array Data Channels.vi" after you refactor the "Validate Channel or Section Name.vi"
> 
> image

Fixed as requested.

**Comment by zszilagy** [comment]
> Create Data Channel - Array - Type Cast.vi -> The enum marked below should have the value "Type Cast".
> 
> image

Fixed as requested.

**Comment by zszilagy** [comment]
> For all "Create Data Channels" please correct this typo in the VI documentation (correct: "Refnum"):
> 
> image

Fixed as requested.

**Comment by zszilagy** [comment]
> For all "Create Data Channels" of Array Type. I find the current Documentation wording a bit confusing.
> 
> I would adapt it to something similar to the below:
> 
> _Creates a new Data Channel with the following configuration:
> Data Type: Array
> Channel Type: {enum, format, etc.}
> 
> It also creates all the channel elements specified in the "Elements" array from the "Settings" input.
> 
> Input:
> Message Refnum In: reference to the "Response" message section.
> Name: represents the desired name of the Data Channel
> Settings: represents the settings applied as well as the settings for each element which will be added to the Data Channel
> 
> Output:
> Message Refnum Out: reference to the "Response" message section used as input.
> Channel Refnums: reference to the newly created Data Channel section._

Fixed as requested.

**Comment by zszilagy** [comment]
> Create Data Channel - Array - Comparison.vi -> The marked enum should have the value "Comparison".
> 
> image

Fixed as requested.

**Comment by zszilagy** [comment]
> Validate Channel or Array Name.vi -> The specified error codes are already taken. Please use the next incremental error codes available in the "Instrument Addon Scripting Error Codes" document and update the info there.
> 
> image

VI is not used/ Removed from the project/folder.

**Comment by zszilagy** [comment]
> > Validate Channel or Array Name.vi -> The specified error codes are already taken. Please use the next incremental error codes available in the "Instrument Addon Scripting Error Codes" document and update the info there.
> > image
> 
> Is this VI used somewhere? I am having a hard time finding the a caller VI for it.

VI is not used/ Removed from the project/folder.

**Comment by zszilagy** [comment]
> We need to add an additional check in all the unit tests to check for the correct type of the Channels created.
> The current unit tests failed to identify the wrong enum value for "Create Data Channel - Array - Comparison.vi" and "Create Data Channel - Array - Type Cast.vi"

Added two asserts in the each test which verifies the Data Type and Channel Type of the Channel.

**Comment by phutanu** [comment]
Throw Invalid Name Error.vi -> Should be removed as it is not used anymore.

**Comment by phutanu** [comment]
System Explorer.lvlib--Add Data Channels.vi -> How does the Array Elements Creation in System Explorer works now? Because from what I notice in the current implementation is that we add two index numbers at the end of each Channel Name instead of one.

image

**Comment by phutanu** [comment]
> System Explorer.lvlib--Add Data Channels.vi -> How does the Array Elements Creation in System Explorer works now? Because from what I notice in your implementation is that we add two index numbers at the end of each Array Channel Element instead of only one.
> 
> Something like:
> Array Element 0 0
> Array Element 1 1
> and so on...
> 
> Instead of having:
> Array Element 0
> Array Element 1
> and so on...
> 
> image
> 
> If my assumption is right, then I think we can refactor the code into one VI, as we can discard one of the for loops used to add one of the indexes.
> 
> And based on the original implementation it seems that I am:
> 
> image

Ok, I finally understood. You need to remove the current "System Explorer.lvlib--Add Data Channels.vi" node and use "Instrument Addon Scripting API.lvlib--Add Array Data Channels.vi". The one from system explorer should be deleted.

**Comment by phutanu** [comment]
Sorry I did not mention this on the first pass. 😭 
Is there a reason you added a space at the end of each test name? If not, please remove them.

👍 a **big like** on how the tests are looking now. I do think that now we have a very high test coverage.

**Comment by phutanu** [comment]
Thanks for addressing everything from the first pass and also taking the time to reply to all my comments. ❤️

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check the new comments.

**Comment by zszilagy** [comment]
> Sorry I did not mention this on the first pass. 😭
> Is there a reason you added a space at the end of each test name? If not, please remove them.
> 
> 👍 a **big like** on how the tests are looking now. I do think that now we have a very high test coverage.

Removed the extra space.

**Comment by zszilagy** [comment]
> > System Explorer.lvlib--Add Data Channels.vi -> How does the Array Elements Creation in System Explorer works now? Because from what I notice in your implementation is that we add two index numbers at the end of each Array Channel Element instead of only one.
> > Something like:
> > Array Element 0 0
> > Array Element 1 1
> > and so on...
> > Instead of having:
> > Array Element 0
> > Array Element 1
> > and so on...
> > image
> > If my assumption is right, then I think we can refactor the code into one VI, as we can discard one of the for loops used to add one of the indexes.
> > And based on the original implementation it seems that I am:
> > image
> 
> Ok, I finally understood. You need to make sure you are using the "Instrument Addon Scripting API.lvlib--Add Array Data Channels.vi" inside the "System Explorer.lvlib--Add Data Channels.vi".
> 
> Both "Instrument Addon Scripting API.lvlib--Add Array Data Channels.vi" and "System Explorer.lvlib--Add Array Data Channels.vi" have the same icon and name (hence the confusion), but the System Explorer one should not be used in the current implementation as it will change the behavior as described above.
> 
> The "System Explorer.lvlib--Add Array Data Channels.vi" should be deleted.

Removed the extra file.

**Comment by zszilagy** [comment]
> Throw Invalid Name Error.vi -> Should be removed as it is not used anymore.

Removed the file.

**Comment by zszilagy** [comment]
> Please check the new comments.

Done!

**Comment by phutanu** [comment]
Remove Target from Path.vi -> Should be reverted from the last commit, as change as been made to it.

**Comment by phutanu** [comment]
Scripting API/SubVIs/NodeID to Channel Pointer.vi -> Should this physical file be removed? It was removed from the Scripting Library file, and there is one in the Shared Library that it is used in the API nodes.

**Comment by phutanu** [comment]
Set Message Trigger.vi -> Why do we need to make this change?

**Comment by phutanu** [comment]
I notice that in "Resolve ByteCount Wait.vi" and in "Resolve Seconds Wait.vi" you used "Instrument Addon Shared.lvlib--NodeID to Channel Pointer.vi" but I do not see this VI in the Shared.lvlib from the repo main branch, and it was not added in the Shared lvlib as a change in your PR.

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check my above comments.

**Comment by bogdanp-ni** [comment]
For the tearDown VI, if one of the Close nodes errors out, then the rest of the references will not be closed properly. Instead, rewire the error out from all Close nodes somewhere at the end:

image

**Comment by bogdanp-ni** [comment]
[Recommend] test_Add Array Comparison -> extract this into a subVI:

image

**Comment by bogdanp-ni** [comment]
[Recommend] When comparing with constant values, it's a good habit to display the value of the constant (instead of just the icon), for better readability:

image

**Comment by bogdanp-ni** [comment]
Please rename the tests: **test_Create Data Channel_array format** or **test_Create Data Channel_single channel enumerated list**.
I know it's a pain,but it will help us in the long run.

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See my above comments.

**Comment by zszilagy** [comment]
> Remove Target from Path.vi -> Should be reverted to the version from main, as no change has been made to it.

It was modified accidentally, however I observed that the reference comming out from the StringArrayToNodePathUtils invoke node is not closed. I added a close ref node just to stay on the safe side.

**Comment by zszilagy** [comment]
> Set Message Trigger.vi -> Why do we need to make this change in this PR? what does it fix?
> 
> If we need to fix it in this PR, we can also replace the highlighted code with "Remove Target from Path.vi"
> image
> 
> image

Fixed the issue and refactored the VI as requested.

**Comment by zszilagy** [comment]
> For the tearDown VI, if one of the Close nodes errors out, then the rest of the references will not be closed properly. Instead, rewire the error out from all Close nodes somewhere at the end:
> 
> image

Fixed as suggested.

**Comment by zszilagy** [comment]
> Please rename the tests: **test_Create Data Channel_array format** or **test_Create Data Channel_single channel enumerated list**.
> I know it's a pain,but it will help us in the long run.

Modified as requested.

**Comment by zszilagy** [comment]
> [Recommend] When comparing with constant values, it's a good habit to display the value of the constant (instead of just the icon), for better readability:
> 
> image

Good point. Modified as requested.

**Comment by zszilagy** [comment]
> [Recommend] test_Add Array Comparison -> extract this into a subVI:
> 
> image

I refactored the VI and moved the implementation details to separate subVIs.

**Review by phutanu — APPROVED** [review]

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
