### PR TITLE
Refactored command API to separate the Add Command node and the Configure node

### PR DESCRIPTION
**Pull request by csteavu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Split the old Add Command VI into 2 (Add Command and Configure Command)

### Why should this Pull Request be merged?

To satisfy the updated feature spec

### What testing has been done?

Important note !! There are no tests modified because of the fluctuating NodeID bug.
The tests will be refactored to reflect the new node structure after pull 117 is in.
Along with that refactor, the tests will gain aditional robustness by implementing similar refactors as in pull 117.

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
The public node should be called "Create Command", not "Add Command".

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
There's still an Add Command here, along with Create and Configure:

image

**Comment by phutanu** [comment]
Configure Command.vi.png -> as this node is a top level one, we should validate that the refnum given as input is coming from a command, and report an error if otherwise. You can add the node in the marked part below.
You can make the node similar with "Validate Message Refnum.vi".

image

**Review by phutanu — CHANGES_REQUESTED** [review]
Configure Command.vi.png -> as this node is a top level one, we should validate that the refnum given as input is coming from a command, and report an error if otherwise. You can add the node in the marked part below.
You can make the node similar with "Validate Message Refnum.vi".

image

**Comment by phutanu** [comment]
Also, please make sure that both top level nodes "Create Command.vi" and "Configure Command.vi" have a one, or two lines of documentation describing the basic functionality. There is no need to describe each individual input.

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
I sync-ed these changes locally and it seems some files are not correctly added in the libraries, because LV doesn't find them and I have to manually specify those paths manually. For example, it is looking for "Add Command", which was removed (it should be looking for "Add Message Command", instead). Please fix these issues and test them in another workspace, if necessary.

**Comment by zszilagy** [comment]
> Configure Command.vi.png -> as this node is a top level one, we should validate that the refnum given as input is coming from a command, and report an error if otherwise. You can add the node in the marked part below.
> You can make the node similar with "Validate Message Refnum.vi".
> 
> image

Implemented the Validate Command Refnum.vi

**Comment by zszilagy** [comment]
> I sync-ed these changes locally and it seems some files are not correctly added in the libraries, because LV doesn't find them and I have to manually specify those paths manually. For example, it is looking for "Add Command", which was removed (it should be looking for "Add Message Command", instead). Please fix these issues and test them in another workspace, if necessary.

Fixed the dependency issues in the project. (tests and VIs)

**Comment by zszilagy** [comment]
> Also, please make sure that both top level nodes "Create Command.vi" and "Configure Command.vi" have a one, or two lines of documentation describing the basic functionality. There is no need to describe each individual input.

csteavu implemented this.

**Comment by phutanu** [comment]
Validate Command Refnum.vi -> This Error Logic needs to be refactored, because currently, if the System Definition Property node will return an internal error -> the "GUID output" will be different than the expected "Command GUID" and we will output our defined error, but not the true source of error. And that will lead to a lot of confusion for the API users as they will need to do some debugging to identify the true source of error. 

image

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check my above comment.

**Comment by bogdanp-ni** [comment]
> Validate Command Refnum.vi -> The Error Logic below needs to be refactored, because currently, if the System Definition Property node will return an internal error -> the "GUID output" will be different than the expected "Command GUID" and we will output our defined error, but not the true source of error. And that will lead to a lot of confusion for the API users as they will need to do some debugging to identify the true source of error.
> 
> image

+1 on this. If the inequality condition holds, then merge the incoming error wire with the 5025 error.

**Comment by bogdanp-ni** [comment]
I don't want you to make the following changes now, I'd like to wrap up this PR soon, but for future instances that require error testing, please read my comments from https://github.com/ni/niveristand-instrument-addon-custom-device/pull/117 on how to structure such testcases.

**Review by bogdanp-ni — APPROVED** [review]
I'm ok with this PR, as long as phutanu's comments are addressed.

**Comment by zszilagy** [comment]
> Validate Command Refnum.vi -> The Error Logic below needs to be refactored, because currently, if the System Definition Property node will return an internal error -> the "GUID output" will be different than the expected "Command GUID" and we will output our defined error, but not the true source of error. And that will lead to a lot of confusion for the API users as they will need to do some debugging to identify the true source of error.
> 
> image

Fixed.

**Comment by zszilagy** [comment]
> > Validate Command Refnum.vi -> The Error Logic below needs to be refactored, because currently, if the System Definition Property node will return an internal error -> the "GUID output" will be different than the expected "Command GUID" and we will output our defined error, but not the true source of error. And that will lead to a lot of confusion for the API users as they will need to do some debugging to identify the true source of error.
> > image
> 
> +1 on this. If the inequality condition holds, then merge the incoming error wire with the 5025 error.

Implemented as requested.

**Pull request merged**
