### PR TITLE
Added extra layer of verification which validates if the message name is not empty string or existing name

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Implements an extra layer of verification in the Create Message.vi which makes sure that the message name is not an emptystring or it's not an already existing name.
Also created a few tests to validate the behavior.

### Why should this Pull Request be merged?

Currently it's possible to create Messages with identical name through scripting API.

### What testing has been done?

Run all the message unit tests and they all passed.
Built the scripting API and Configuration release locally and the build passed in both occasions.

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Typo here:

image

**Comment by bogdanp-ni** [comment]
Use lowercase here - 'message name':

image

**Comment by bogdanp-ni** [comment]
Please add these new errors to the review list, if you didn't already :)

**Review by bogdanp-ni — APPROVED** [review]
Fix the typos and you're good to go.

**Comment by zszilagy** [comment]
> Typo here:
> 
> image

Fixed.

**Comment by zszilagy** [comment]
> Use lowercase here - 'message name':
> 
> image

Fixed.

**Review by bogdanp-ni — APPROVED** [review]

**Comment by phutanu** [comment]
Please correct this small typos:
"Message G_r_oup in" and "Message G_r_oup out".

image

**Review by phutanu — APPROVED** [review]
Only the typo mentioned above, and this is good to go from my side also.

**Comment by zszilagy** [comment]
> Please correct this small typos:
> "Message G _r_ oup in" and "Message G _r_ oup out".
> 
> image

Fixed.

**Review by phutanu — APPROVED** [review]

**Pull request merged**
