### PR TITLE
Added GET and SET PCL Decimation.vi functionality

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Added GET/SET PCL Decimation.vi functionality.
Added a test which verifies the functionality of the get/set VIs. 
Deleted the Decimation FG.vi and replaced every instance with the newly created Get/Set PCL Decimation.vi in the Instrument Addon Custom device.

### Why should this Pull Request be merged?

The functionality of the Get PCL Decimation.vi and Set PCL Decimation.vi was not implemented in the ScriptingAPI until now. 
We intend to use the new scripting API in Instrument Addon custom device, hence the changes in the Instrument Addon code.

### What testing has been done?

Run the new unit test locally and it passed.
Built the Engine/Configuration build specs in order to make sure that nothing was ruined in the IA.

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Just a minor detail: always remove all TODOs from PR description.

**Comment by bogdanp-ni** [comment]
Was it necessary to save the lvproj?

**Comment by phutanu** [comment]
@bogdanp-ni: I assume for data types we stick with what is currently implemented in the instrument addon? For example "Decimation" is U32 in the addon, and U16 in the Spec.

**Comment by phutanu** [comment]
@bogdanp-ni: Should we make the "Decimation" input for the Set PCL Decimation a required one?

**Comment by bogdanp-ni** [comment]
> @bogdanp-ni: I assume for data types we stick with what is currently implemented in the instrument addon? For example "Decimation" is U32 in the addon, and U16 in the Spec.

Yes, let's stick to U32.

**Comment by bogdanp-ni** [comment]
> @bogdanp-ni: Should we make the "Decimation" input for the Set PCL Decimation a required one?

Yes, required.

**Comment by phutanu** [comment]
Please solve the conflicted file and make the "Decimation" input to be required in the "Set PCL Decimation.vi".

**Comment by zszilagy** [comment]
> Please solve the conflicted file and make the "Decimation" input to be required in the "Set PCL Decimation.vi".

Done!

**Comment by phutanu** [comment]
> Was it necessary to save the lvproj?

**Comment by zszilagy** [comment]
> > Was it necessary to save the lvproj?

I think the project became dirty when I updated the assembly version from 2016 to 2018. @DStavilaNI did you also change the assembly on your machine? Did the project became dirty afterwards?

**Comment by zszilagy** [comment]
> > > Was it necessary to save the lvproj?
> 
> I think the project became dirty when I updated the assembly version from 2016 to 2018. @DStavilaNI did you also change the assembly on your machine? Did the project became dirty afterwards?

Never mind, I rolled back the lvrpoj file. It no longer appears in the modified files list.

**Comment by phutanu** [comment]
The PCL decimation default value should be 1. Please update the input Control "PCL Decimation" and the documentation for the "Set PCL Decimation.vi".

**Comment by zszilagy** [comment]
> The PCL decimation default value should be 1. Please update the input Control "PCL Decimation" and the documentation for the "Set PCL Decimation.vi".

Modification submitted

**Comment by bogdanp-ni** [comment]
Rename: "Check refnum if its IA CD.vi" -> "Validate IA Refnum.vi"

**Comment by bogdanp-ni** [comment]
In the test for Get and Set, add another Get PCL Decimation before doing the Set. The expected value should be the one from the sysdef.

**Comment by DStavilaNI** [comment]
> 
> 
> > > > Was it necessary to save the lvproj?
> > 
> > 
> > I think the project became dirty when I updated the assembly version from 2016 to 2018. @DStavilaNI did you also change the assembly on your machine? Did the project became dirty afterwards?
> 
> Never mind, I rolled back the lvrpoj file. It no longer appears in the modified files list.

Just to answer this - the project loads the assemblies via the Advanced System Definition API ... so if you configure the Advanced System Definition API to load the proper assemblies (as you probably did :) ) the project will not notice any changes. This is why it does not appear as modified.

**Comment by bogdanp-ni** [comment]
In  "Check refnum if its IA CD.vi", the Refnum output seems to be a plain U64, instead of the expected typedef.

**Comment by bogdanp-ni** [comment]
After renaming  "Check refnum if its IA CD.vi", please change the icon text to "Valid IA Ref?"

**Review by bogdanp-ni — APPROVED** [review]

**Review by phutanu — APPROVED** [review]

**Pull request merged**
