### PR TITLE
Updated the Context help for the VIs

### PR DESCRIPTION
**Pull request by csteavu**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Changed the Documentation for the VIs to be in accordance with the feedback from Will

### Why should this Pull Request be merged?

Context help was updated and VIs don't reflect that

### What testing has been done?

N/A

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
For the "Export" VI, remove the second sentence, it is not true anymore (no dialog box will appear, but an error will be thrown): 
image

**Comment by bogdanp-ni** [comment]
Create Message - seems to be missing any description:

image

**Comment by bogdanp-ni** [comment]
"beginning"

image

**Review by bogdanp-ni — CHANGES_REQUESTED** [review]
See my comments above.

**Comment by csteavu** [comment]
> Create Message - seems to be missing any description:
> 
> image

image
I will push the changes and revisit this... as it seems the description is already added

**Comment by csteavu** [comment]
Implemented the feedback. For Create Command and Create Response , I changed the "Add or Create" to just "Create"

**Comment by phutanu** [comment]
Configure Command.vi -> Please update the marked texts with:
- Linked Channels
- Variables Names

For consistency with the rest of the implementation.

image

**Comment by phutanu** [comment]
Create Message - Trigger Only.vi -> replace "fits" with "best used" as per Will's instructions.

image

**Comment by phutanu** [comment]
> > Create Message - seems to be missing any description:
> > image
> 
> image
> I will push the changes and revisit this... as it seems the description is already added

This should be the final version used for this VI:

"Creates a new message section. 
The Generation Type can be set to Trigger Only, Periodic & Trigger, or Value Change & Trigger."

**Comment by phutanu** [comment]
Can you please post snips for:
- Create Message - Value Change & Trigger.vi.png
- Create Message - Periodic & Trigger.vi

DiffBot is having a hard time showing details for this two VIs. I did not find them in any of the generated diffs above... :(

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check my small remarks.

**Comment by bogdanp-ni** [comment]
One more thing: please make sure to be consistent across the board when using "metadata/data channels" vs "MetaData/Data Channels" by following our tech writer's recommendations on this matter.

**Review by bogdanp-ni — APPROVED** [review]

**Comment by csteavu** [comment]
> Can you please post snips for:
> 
> * Create Message - Value Change & Trigger.vi.png
> * Create Message - Periodic & Trigger.vi
> 
> DiffBot is having a hard time showing details for this two VIs. I did not find them in any of the generated diffs above... :(

image

image

**Review by phutanu — CHANGES_REQUESTED** [review]
Please solve the marked conflicted files, and after the PR is in a good state I will continue the review on the addressed feedback.

**Comment by phutanu** [comment]
[Recommendation] Protocol Factory.vi 
I know that the current version was discussed with Will, but it does not sound right. I would suggest we change the highlighted to -> "using the polymorphic VI selector.".

image

**Comment by phutanu** [comment]
Get Protocol Type.vi -> as the terminal names changed after the API review, the below needs to be updated:

"Returns a "protocol type" Enum matching the protocol wired to the "protocol in" terminal."

image
image

**Review by phutanu — APPROVED** [review]
I left a recommendation and one small change that I would like to see addressed, before merging. But otherwise this seems to be ok as agreed with Will.

**Review by phutanu — APPROVED** [review]

**Pull request merged**
